// Content for the subjects beyond electricity. Card shape matches the electricity cards:
// { e, n, sh, what, like, home[], q, a, tr, adult?, sym?, symNote? }

const card = (module_id, prefix) => (id, level, sort, data) => ({ id: `${prefix}-${id}`, module_id, level, sort, data });
const q = (module_id, prefix) => (n, question, options, answer, explanation) =>
  ({ id: `${prefix}-q${n}`, module_id, question, options, answer, explanation, sort: n });

// ───────────────────────── Inside a Computer ─────────────────────────
const c = card("computer", "pc");
export const COMPUTER_LEVELS = [
  { id: 0, name: "Big ideas", note: "Start here" },
  { id: 1, name: "Input", note: "How a computer senses" },
  { id: 2, name: "CPU and memory", note: "How it follows instructions and remembers" },
  { id: 3, name: "Output", note: "How it shows and tells" },
];
export const COMPUTER_CARDS = [
  c("computer", 0, 0, { e: "💻", n: "Computer", sh: "A machine that follows instructions",
    what: "A computer is a machine that follows instructions very, very fast. It can do sums, play videos, show games and talk to other computers.",
    like: "A super-fast helper who does exactly what the instructions say, nothing more and nothing less.",
    home: ["Laptop and desktop", "Mobile phone (a small computer!)", "Smart TV", "ATM machine", "Washing machine has a tiny one"],
    q: "Is a mobile phone a computer?", a: "Yes! It takes input, thinks, remembers and shows output, just like a laptop.",
    tr: "Count how many computers are in your house. Remember that phones and smart TVs count!" }),
  c("ipo", 0, 1, { e: "🔁", n: "Input → Process → Output", sh: "How every computer works",
    what: "Every computer does three things. It takes something in (input), thinks about it (process) and gives something out (output).",
    like: "Making a sandwich. Bread and jam go in, you put it together, and a sandwich comes out.",
    home: ["Calculator: press 2 + 2 (input), it adds (process), shows 4 (output)", "Microwave: press start, it heats, it beeps"],
    q: "In a calculator, what is the input and what is the output?", a: "The buttons you press are the input. The number on the screen is the output.",
    tr: "Play “sandwich computer”. You say the input, a parent does the process, and out comes the output!" }),
  c("program", 0, 2, { e: "📜", n: "Program", sh: "A list of instructions",
    what: "A program is a list of steps that tells the computer what to do, in the right order. Games, apps and videos are all programs.",
    like: "A recipe. Follow the steps in order and you get a cake.",
    home: ["Every app on the phone", "Games", "The washing machine's wash cycle"],
    q: "What happens if the steps in a recipe are in the wrong order?", a: "The cake goes wrong! Computers also need steps in the right order.",
    tr: "Write a 5-step program for brushing your teeth. Can a parent follow it exactly?" }),
  c("bug", 0, 3, { e: "🐞", n: "Bug", sh: "A mistake in the instructions",
    what: "A bug is a mistake in a program. Finding and fixing bugs is called debugging. Every programmer makes bugs, even the best ones!",
    like: "Writing “turn left” when you meant “turn right” in directions to a friend's house.",
    home: ["An app that freezes", "A game character stuck in a wall"],
    q: "Is it bad to make a bug?", a: "No! Everyone makes bugs. Finding and fixing them is how we learn.",
    tr: "In the Coding Puzzles, make a mistake on purpose, then fix it." }),
  c("keyboard", 1, 4, { e: "⌨️", n: "Keyboard", sh: "Type letters in",
    what: "A keyboard sends letters, numbers and commands into the computer when you press the keys.",
    like: "Talking to the computer with your fingers.",
    home: ["Laptop keyboard", "Phone's on-screen keyboard", "ATM number pad"],
    q: "Is the keyboard input or output?", a: "Input. It sends information into the computer.",
    tr: "Find the letters of your name on a keyboard and type it." }),
  c("mouse", 1, 5, { e: "🖱️", n: "Mouse and touchpad", sh: "Point and click",
    what: "A mouse tells the computer where you are pointing and when you click.",
    like: "Pointing at something with your finger and saying “this one!”",
    home: ["Computer mouse", "Laptop touchpad"],
    q: "Why is it called a mouse?", a: "The first ones were small with a long wire like a tail!",
    tr: "Move the mouse slowly and watch the arrow follow your hand." }),
  c("touch", 3, 14, { e: "📱", n: "Touch screen", sh: "Input AND output",
    what: "A touch screen shows pictures (output) and feels your finger (input) at the same time.",
    like: "A magic slate that can see where you touch.",
    home: ["Mobile phone", "Tablet", "Ticket machines at the metro"],
    q: "Is a touch screen input or output?", a: "Both! It shows things and it feels your touch.",
    tr: "Try touching a phone with a glove on. Does it work? (Most don't: the screen feels the electricity in your finger!)" }),
  c("camera", 1, 7, { e: "📷", n: "Camera and microphone", sh: "The computer's eyes and ears",
    what: "A camera lets a computer see pictures and a microphone lets it hear sounds.",
    like: "Our eyes and ears.",
    home: ["Phone camera", "Laptop webcam", "Voice assistants"],
    q: "Which sense is a microphone like?", a: "Hearing, like our ears.",
    tr: "Take a photo on a phone and zoom in. The picture is made of tiny coloured squares (pixels)!" }),
  c("cpu", 2, 8, { e: "🧠", n: "CPU (processor)", sh: "Follows instructions, super fast",
    what: "The CPU follows the program's instructions, billions of tiny steps every second. People call it the computer's brain, but it can't think on its own: it only follows instructions.",
    like: "A super-fast cook following a recipe exactly. Great at following steps, but it can't invent a new dish by itself.",
    home: ["Inside every laptop and phone", "Games consoles"],
    q: "Can the CPU think for itself?", a: "No! It only follows instructions, but it does billions of them every second.",
    tr: "Race a calculator: who can add 2468 + 1357 faster, you or the calculator?" }),
  c("ram", 2, 9, { e: "📝", n: "Memory (RAM)", sh: "Short-term notebook",
    what: "RAM is the computer's short-term memory. It keeps what you are working on right now. When the power goes off, it forgets!",
    like: "A whiteboard. Useful while you work, but wiped clean at the end of the day.",
    home: ["Inside laptops, phones and tablets"],
    q: "What happens to RAM when you switch the computer off?", a: "It forgets everything in it. That's why we save our work.",
    tr: "Play a memory game: remember 5 things on a tray, then look away. That's your RAM!" }),
  c("storage", 2, 10, { e: "🗄️", n: "Storage", sh: "Long-term cupboard",
    what: "Storage keeps photos, videos, games and files even when the computer is switched off.",
    like: "A cupboard or a bookshelf. Things stay there until you take them out.",
    home: ["Phone storage full of photos", "Pen drive", "Memory card in a camera"],
    q: "Where do your photos stay when the phone is switched off?", a: "In the storage, like a cupboard.",
    tr: "Look at a phone's storage settings with a parent. What takes the most space?" }),
  c("screen", 3, 11, { e: "🖥️", n: "Screen", sh: "Shows pictures",
    what: "A screen shows words, pictures and videos. It is made of millions of tiny coloured dots called pixels.",
    like: "A mosaic made of tiny coloured tiles.",
    home: ["TV", "Laptop screen", "Phone screen", "Digital boards at railway stations"],
    q: "What are pixels?", a: "Tiny coloured dots that make up every picture on a screen.",
    tr: "Put a drop of water on a phone screen (with a parent). The drop works like a magnifier and you can see pixels!", adult: true }),
  c("speaker", 3, 12, { e: "🔊", n: "Speaker", sh: "Makes sound",
    what: "A speaker turns the computer's signals into sounds you can hear.",
    like: "The computer's mouth.",
    home: ["Phone speaker", "TV", "Bluetooth speaker", "Headphones"],
    q: "Is a speaker input or output?", a: "Output. The sound comes out of the computer.",
    tr: "Turn the volume up and down. Which button is input and what comes out as output?" }),
  c("printer", 3, 13, { e: "🖨️", n: "Printer", sh: "Puts it on paper",
    what: "A printer takes what is on the screen and puts it on paper with ink.",
    like: "A robot that draws exactly what the computer tells it.",
    home: ["Home or office printer", "Bill printer at the shop", "Ticket printer on the bus"],
    q: "When the shopkeeper gives you a bill, which computer part made it?", a: "A printer! That's output on paper.",
    tr: "Draw a picture on the computer and print it with a parent." }),
];
const cq = q("computer", "pc");
export const COMPUTER_QUIZ = [
  cq(1, "Which one is INPUT?", [{ label: "Keyboard", emoji: "⌨️" }, { label: "Screen", emoji: "🖥️" }, { label: "Printer", emoji: "🖨️" }], 0, "A keyboard sends information into the computer."),
  cq(2, "Which part is the computer's brain?", [{ label: "Speaker", emoji: "🔊" }, { label: "CPU", emoji: "🧠" }, { label: "Mouse", emoji: "🖱️" }], 1, "The CPU does all the thinking."),
  cq(3, "Where do photos stay when the phone is off?", [{ label: "RAM", emoji: "📝" }, { label: "Storage", emoji: "🗄️" }, { label: "Screen", emoji: "🖥️" }], 1, "Storage is the long-term cupboard."),
  cq(4, "What is a list of instructions called?", [{ label: "Program", emoji: "📜" }, { label: "Pixel", emoji: "🟥" }, { label: "Printer", emoji: "🖨️" }], 0, "A program is like a recipe for the computer."),
  cq(5, "Which one is OUTPUT?", [{ label: "Microphone", emoji: "🎤" }, { label: "Camera", emoji: "📷" }, { label: "Speaker", emoji: "🔊" }], 2, "Sound comes out of the speaker."),
  cq(6, "A mistake in a program is called a…", [{ label: "Bug", emoji: "🐞" }, { label: "Byte", emoji: "8️⃣" }, { label: "Mouse", emoji: "🖱️" }], 0, "Fixing bugs is called debugging."),
  cq(7, "What forgets everything when the power goes off?", [{ label: "Storage", emoji: "🗄️" }, { label: "RAM", emoji: "📝" }, { label: "Pen drive", emoji: "💾" }], 1, "RAM is like a whiteboard that is wiped clean."),
  cq(8, "A touch screen is…", [{ label: "Only input", emoji: "👆" }, { label: "Only output", emoji: "🖥️" }, { label: "Both!", emoji: "📱" }], 2, "It shows pictures and feels your finger."),
];

// ───────────────────────── Binary ─────────────────────────
const b = card("binary", "bin");
export const BINARY_LEVELS = [
  { id: 0, name: "Big ideas", note: "How computers count" },
  { id: 1, name: "Bits in real life", note: "Letters, pictures and more" },
];
export const BINARY_CARDS = [
  b("onoff", 0, 0, { e: "💡", n: "ON and OFF", sh: "Computers only know two things",
    what: "Deep inside, a computer only understands two things: ON and OFF. We write ON as 1 and OFF as 0.",
    like: "A light switch. It can only be on or off.",
    home: ["Light switches", "The transistors in every chip"],
    q: "How many different things can one switch show?", a: "Two: ON (1) or OFF (0).",
    tr: "Flip a light switch and say “one” for ON and “zero” for OFF." }),
  b("bit", 0, 1, { e: "🔘", n: "Bit", sh: "One ON or OFF",
    what: "A bit is one single ON or OFF, a single 1 or 0. It is the smallest piece of information in a computer.",
    like: "One light bulb in a long row of bulbs.",
    home: ["Every photo, song and game is made of bits"],
    q: "What are the only two values a bit can have?", a: "0 and 1.",
    tr: "Hold up one hand: open is 1, closed is 0. You are a bit!" }),
  b("counting", 0, 2, { e: "🔢", n: "Binary counting", sh: "Counting with 1, 2, 4, 8, 16",
    what: "Binary uses cards worth 1, 2, 4, 8 and 16. Each card is either ON or OFF. Add up the ON cards to get the number. So 5 is 4 + 1.",
    like: "Paying with coins of 1, 2, 4, 8 and 16 rupees, using each coin at most once.",
    home: ["Every number inside a computer", "Digital clocks count in binary inside"],
    q: "Which cards make 6?", a: "4 and 2! (4 + 2 = 6)",
    tr: "Open the Binary Cards activity and make your age." }),
  b("byte", 1, 3, { e: "🔤", n: "Letters are numbers", sh: "A = 65",
    what: "Computers store letters as numbers. Capital A is 65, B is 66, C is 67, and so on. Eight bits together are called a byte, and one byte can hold one letter.",
    like: "A secret code where every letter has a number.",
    home: ["Every message you type", "Your name in an app"],
    q: "If A is 65 and B is 66, what is C?", a: "67!",
    tr: "Write a secret message using A=1, B=2, C=3… and let a parent decode it." }),
  b("pixels", 1, 4, { e: "🟥", n: "Pictures are numbers", sh: "Pixels have number colours",
    what: "Every picture is made of tiny squares called pixels. Each pixel's colour is stored as numbers, which the computer keeps as bits.",
    like: "Colour-by-number drawings.",
    home: ["Phone photos", "Video games", "TV pictures"],
    q: "What are the tiny squares in a picture called?", a: "Pixels.",
    tr: "On squared paper, colour boxes black (1) or white (0) to draw a smiley face in binary." }),
  b("doubling", 0, 5, { e: "✨", n: "Doubling", sh: "Each new bit doubles it",
    what: "Every new bit doubles the number of patterns: 1 bit makes 2 patterns, 2 bits make 4, 3 bits make 8, and 8 bits make 256.",
    like: "Folding paper: every fold doubles the number of layers.",
    home: ["Card values 1, 2, 4, 8, 16", "Phone storage sizes: 32, 64, 128, 256 GB"],
    q: "How many patterns can 3 bits make?", a: "8! (2 × 2 × 2)",
    tr: "Fold a sheet of paper in half three times, open it and count the boxes: 8." }),
  b("eightbits", 1, 6, { e: "🧺", n: "Byte", sh: "8 bits together",
    what: "A byte is 8 bits together. One byte can store a number from 0 to 255, or one English letter.",
    like: "A team of 8 light switches working together.",
    home: ["File sizes are counted in bytes", "Each letter you type"],
    q: "How many bits are in one byte?", a: "8 bits.",
    tr: "Write your name and count the letters. That is about how many bytes it needs." }),
  b("sizes", 1, 7, { e: "💾", n: "KB, MB and GB", sh: "Kilo, mega, giga",
    what: "A kilobyte (KB) is about a thousand bytes, a megabyte (MB) about a million, and a gigabyte (GB) about a billion. A song is about 4 MB; a phone may store 64 GB or more.",
    like: "A cup, a bucket and a water tank: each holds about a thousand times more.",
    home: ["Phone storage: 64 GB, 128 GB", "Photo and app sizes"],
    q: "Which is bigger: 1 GB or 1 MB?", a: "1 GB. It is about a thousand times bigger.",
    tr: "With a grown-up, open a phone's storage settings and find the biggest app." }),
];
const bq = q("binary", "bin");
export const BINARY_QUIZ = [
  bq(1, "Inside a computer, everything is stored as…", [{ label: "0 and 1", emoji: "🔘" }, { label: "A to Z", emoji: "🔤" }, { label: "Colours", emoji: "🎨" }], 0, "Everything is ON (1) or OFF (0)."),
  bq(2, "Which cards make 3?", [{ label: "2 + 1", emoji: "✌️" }, { label: "4 + 1", emoji: "🖐️" }, { label: "8", emoji: "🎱" }], 0, "2 + 1 = 3."),
  bq(3, "One single 0 or 1 is called a…", [{ label: "Byte", emoji: "8️⃣" }, { label: "Bit", emoji: "🔘" }, { label: "Pixel", emoji: "🟥" }], 1, "A bit is the smallest piece."),
  bq(4, "Which number is 8 + 2?", [{ label: "10", emoji: "🔟" }, { label: "6", emoji: "6️⃣" }, { label: "82", emoji: "🔢" }], 0, "Add the ON cards: 8 + 2 = 10."),
  bq(5, "Tiny squares in a picture are called…", [{ label: "Bugs", emoji: "🐞" }, { label: "Pixels", emoji: "🟥" }, { label: "Bits", emoji: "🔘" }], 1, "Every picture is made of pixels."),
  bq(6, "How many cards are ON to make 31?", [{ label: "All five", emoji: "🖐️" }, { label: "One", emoji: "☝️" }, { label: "None", emoji: "✊" }], 0, "16 + 8 + 4 + 2 + 1 = 31."),
  bq(7, "How many bits make one byte?", [{ label: "8", emoji: "8️⃣" }, { label: "2", emoji: "2️⃣" }, { label: "100", emoji: "💯" }], 0, "8 bits make 1 byte."),
  bq(8, "How many patterns can 3 bits make?", [{ label: "8", emoji: "8️⃣" }, { label: "3", emoji: "3️⃣" }, { label: "6", emoji: "6️⃣" }], 0, "Each bit doubles the patterns: 2 × 2 × 2 = 8."),
  bq(9, "Which is the biggest?", [{ label: "1 GB", emoji: "🛢️" }, { label: "1 MB", emoji: "🪣" }, { label: "1 KB", emoji: "🥛" }], 0, "Giga is bigger than mega, and mega is bigger than kilo."),
  bq(10, "On the 4, 2 and 1 cards, 101 means…", [{ label: "5", emoji: "5️⃣" }, { label: "101", emoji: "💯" }, { label: "3", emoji: "3️⃣" }], 0, "4 is ON, 2 is OFF, 1 is ON: 4 + 1 = 5."),
];

// Bit's binary adventure: the steps shown on the Binary Magic map, in order.
export const BINARY_JOURNEY = [
  { id: "binary-step-1", openFrom: 5, parent: "Point at light switches at home. Everything in a computer is made of tiny switches that are ON or OFF.", emoji: "💡", title: "Bit's lamp", blurb: "Meet Bit. ON and OFF.", learned: "Computers only know two things: ON and OFF." },
  { id: "binary-step-2", openFrom: 5, parent: "Agree a secret signal at home, e.g. porch light ON means “come inside”. One light can only say two things.", emoji: "📡", title: "Secret signal", blurb: "One lamp sends a message.", learned: "One lamp can send 2 different messages." },
  { id: "binary-step-3", openFrom: 5, parent: "Use two torches or two hands up/down. Ask: how many different signals can we make? (4)", emoji: "💡💡", title: "Two lamps", blurb: "Find every pattern.", learned: "Two lamps make 4 patterns, so 4 messages!" },
  { id: "binary-step-4", openFrom: 5, parent: "Ask: if one more lamp doubles the patterns, how many would 5 lamps make? (32) Doubling is the heart of binary.", emoji: "✨", title: "Magic doubling", blurb: "Add a lamp, double the patterns.", learned: "Every new lamp DOUBLES the number of patterns." },
  { id: "binary-step-5", openFrom: 5, parent: "Use real coins or sweets in cups of 1, 2 and 4. Make 1 to 7 by choosing cups; say the lamps as 1s and 0s.", emoji: "🍎", title: "Apple cards", blurb: "Count apples with lamps.", learned: "Add up the apples on the ON cards to get the number. ON is 1, OFF is 0." },
  { id: "binary-step-6", openFrom: 5, parent: "Count 0–7 on three fingers (thumb = 1, pointer = 2, middle = 4). The thumb flips every time: odd and even!", emoji: "🔢", title: "Counting machine", blurb: "Press +1 and watch.", learned: "Binary counting: the last lamp blinks every time." },
  { id: "binary-step-7", openFrom: 5, parent: "Try finger binary on one hand: 5 fingers count to 31. Ask your child to show their age.", emoji: "🃏", title: "Big cards", blurb: "Make bigger numbers.", learned: "You can make any number with doubling cards. You speak binary!" },
  { id: "binary-bonus-pixel", openFrom: 5, parent: "Zoom right into a photo on a phone until you see squares. Each square is a pixel stored as numbers.", emoji: "🖼️", title: "Pixel painter", blurb: "Decode a secret picture.", learned: "Pictures are made of pixels, and pixels are stored as bits.", bonus: true, after: "binary-step-7" },
  { id: "binary-bonus-secret", openFrom: 5, parent: "Write a secret note with A=1, B=2… and let your child decode it.", emoji: "🔐", title: "Secret message", blurb: "Decode Bit's secret words.", learned: "Letters are stored as numbers, and numbers as bits.", bonus: true, after: "binary-step-7" },
];

// ───────────────────────── Coding ─────────────────────────
const k = card("coding", "code");
export const CODING_LEVELS = [{ id: 0, name: "Coding words", note: "Ideas every coder uses" }];
export const CODING_CARDS = [
  k("sequence", 0, 0, { e: "➡️", n: "Sequence", sh: "Steps in order",
    what: "A sequence is a list of steps done one after another, in order.",
    like: "Getting ready for school: wake up, brush, bathe, dress, eat, go.",
    home: ["Morning routine", "Recipe steps", "Washing machine cycle"],
    q: "What happens if you put on shoes before socks?", a: "It goes wrong! Order matters in a sequence.",
    tr: "Put 5 picture cards of your morning in the right order." }),
  k("loop", 0, 1, { e: "🔁", n: "Loop", sh: "Repeat it",
    what: "A loop repeats the same steps again and again, so you don't have to write them many times.",
    like: "Clapping 10 times: you don't say “clap” ten times, you say “clap 10 times”.",
    home: ["Fan blades going round", "Songs with a chorus", "Walking: left, right, left, right…"],
    q: "How would you tell a robot to jump 5 times, quickly?", a: "Use a loop: “Repeat 5 times: jump.”",
    tr: "In Coding Puzzles, use the Repeat block to make a program shorter." }),
  k("condition", 0, 2, { e: "🔀", n: "If… then…", sh: "Making decisions",
    what: "A condition lets a program decide. IF something is true, THEN do one thing, otherwise do something else.",
    like: "IF it is raining, THEN take an umbrella.",
    home: ["Street light: IF dark THEN switch on", "AC: IF too warm THEN cool"],
    q: "Finish this: IF the traffic light is red, THEN…", a: "…stop!",
    tr: "Play “Simon says”. It's all IF… THEN… rules!" }),
  k("algorithm", 0, 3, { e: "🗺️", n: "Algorithm", sh: "A plan to solve a problem",
    what: "An algorithm is a clear plan of steps to solve a problem. A program is an algorithm written for a computer.",
    like: "Directions to a friend's house.",
    home: ["Google Maps finding a route", "Sorting clothes by colour"],
    q: "Is a recipe an algorithm?", a: "Yes! It's a plan of steps to make food.",
    tr: "Write the algorithm for making lemonade." }),
  k("debug", 0, 4, { e: "🔍", n: "Debugging", sh: "Finding and fixing mistakes",
    what: "Debugging means finding the mistake in a program and fixing it. Good coders test often and fix calmly.",
    like: "Checking your sums and correcting a wrong answer.",
    home: ["Fixing a toy that stopped working", "Correcting spelling"],
    q: "Your robot turned the wrong way. What do you do?", a: "Look at each step, find the wrong turn and fix it!",
    tr: "Play “robot parent”. When the parent bumps into something, find the buggy step." }),
  k("variable", 0, 5, { e: "📦", n: "Variable", sh: "A named box for a value",
    what: "A variable is a named box that stores a value, like score = 10. The value can change while the program runs.",
    like: "The scoreboard at a cricket match: the name stays the same, the number keeps changing.",
    home: ["Game scores and lives", "Timers", "Steps counted by a fitness watch"],
    q: "In a game, what could a variable called “lives” store?", a: "How many lives you have left, like 3. It goes down when you get caught!",
    tr: "Keep score in a game of snakes and ladders on paper. That score is a variable." }),
  k("event", 0, 6, { e: "👆", n: "Event", sh: "When something happens…",
    what: "An event is something that happens, like a tap, a key press or a timer ending. Programs wait for events: WHEN the button is tapped, start the game.",
    like: "A doorbell: when someone presses it, the bell rings.",
    home: ["Tapping an app", "An alarm clock going off", "Pressing a lift button"],
    q: "What event starts a video playing on a phone?", a: "Tapping the play button.",
    tr: "Play “When I clap, you jump”. The clap is the event." }),
];
const kq = q("coding", "code");
export const CODING_QUIZ = [
  kq(1, "Steps done in order are called a…", [{ label: "Sequence", emoji: "➡️" }, { label: "Loop", emoji: "🔁" }, { label: "Bug", emoji: "🐞" }], 0, "A sequence is steps in order."),
  kq(2, "Which block repeats steps?", [{ label: "If", emoji: "🔀" }, { label: "Loop", emoji: "🔁" }, { label: "Stop", emoji: "🛑" }], 1, "A loop repeats."),
  kq(3, "“IF it's dark THEN switch on the light” is a…", [{ label: "Condition", emoji: "🔀" }, { label: "Pixel", emoji: "🟥" }, { label: "Battery", emoji: "🔋" }], 0, "IF… THEN… is a condition."),
  kq(4, "Fixing a mistake in a program is called…", [{ label: "Looping", emoji: "🔁" }, { label: "Debugging", emoji: "🔍" }, { label: "Sequencing", emoji: "➡️" }], 1, "Debugging means finding and fixing bugs."),
  kq(5, "A clear plan of steps to solve a problem is called…", [{ label: "An algorithm", emoji: "🗺️" }, { label: "A loop", emoji: "🔁" }, { label: "A bug", emoji: "🐞" }], 0, "An algorithm is a plan of steps. A program is an algorithm written for a computer."),
  kq(6, "A named box that stores a value, like a score, is a…", [{ label: "Variable", emoji: "📦" }, { label: "Loop", emoji: "🔁" }, { label: "Bug", emoji: "🐞" }], 0, "A variable stores a value that can change."),
  kq(7, "“When the button is tapped, start the game.” The tap is an…", [{ label: "Event", emoji: "👆" }, { label: "Algorithm", emoji: "🗺️" }, { label: "Error", emoji: "❌" }], 0, "An event is something that happens, which the program reacts to."),
  kq(8, "“Repeat 3 times: step forward.” How many steps does the robot take?", [{ label: "3", emoji: "3️⃣" }, { label: "1", emoji: "1️⃣" }, { label: "4", emoji: "4️⃣" }], 0, "The loop runs the step forward 3 times."),
];

// Grid puzzles for the Coding Puzzles activity. S = start (facing right), G = goal, # = wall, . = floor.
export const PUZZLES = [
  { id: "p1", title: "First steps", hint: "Move forward until you reach the star.", grid: ["S..G"] },
  { id: "p2", title: "Turn the corner", hint: "Go forward, then turn right to go down.", grid: ["S.#", "#..", "##G"] },
  { id: "p3", title: "Up we go", hint: "Turning left from facing right makes you face up.", grid: ["..G", ".##", "S.."] },
  { id: "p4", title: "Long road", hint: "Tap a block in your program to repeat it: ×2, ×3…", grid: ["S......G"] },
  { id: "p5", title: "Zig-zag", hint: "Forward, right, forward, left… look for a pattern.", grid: ["S.##", "#..#", "##.G"] },
  { id: "p6", title: "Around the wall", hint: "The wall is in the way. Go around it.", grid: ["S#G", ".#.", "..."] },
  { id: "p7", title: "Stairs", hint: "Repeat the same two moves: forward, then down.", grid: ["S.###", "#..##", "##..#", "###.G"] },
  { id: "p8", title: "Big maze", hint: "Plan it on paper first, then build it.", grid: ["S..#G", "##.#.", "...#.", ".###.", "....."] },
  { id: "p9", title: "There and back", hint: "Right to the end, down, then all the way left. Use repeats for the long parts.", grid: ["S....", "####.", "G...."] },
  { id: "p10", title: "Long stairs", hint: "Find the pattern (forward, right, forward, left) and repeat it.", grid: ["S.####", "#..###", "##..##", "###..#", "####.G"] },
  { id: "p11", title: "Spiral", hint: "Go round the outside, turning right each time, then into the middle.", grid: ["S....", "####.", "..G#.", ".###.", "....."] },
];
