// Circuit Lab projects, units 1–4: power and loops, series and parallel, LEDs and resistors,
// conductors. Original projects (see docs/11-circuit-lab-design.md for the format).
// circuit: the reference build in the circuit notation (netlist.js). checks: what must happen;
// any build that passes them is right, whatever its layout.

export const PROJECTS_A = [
  // ───────── Unit 1 · Power and loops ─────────
  { id: "lab-1-1", unit: 1, level: "explorer", emoji: "💡", title: "Light it up",
    q: "How does a switch turn a light on?", goal: "Make a bulb light up with a battery and a switch.",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a n",
    checks: ["S1=off -> L1=off", "S1=on -> L1=on"],
    predict: { q: "The switch is OFF. Will the bulb glow?", options: ["Yes", "No"], answer: 1, why: "OFF opens a gap in the loop, so electricity can't get round." },
    explain: "Electricity flows out of the battery, through the switch and the bulb, and back. Switch ON closes the loop; OFF opens it.",
    world: "Every light switch in your home opens and closes a loop like this one.",
    tryThis: "Move the switch to the other side of the bulb. Does it still work?",
    concepts: ["loop", "switch", "energy"] },
  { id: "lab-1-2", unit: 1, level: "explorer", emoji: "🌀", title: "Fan power",
    q: "How does electricity make things move?", goal: "Make a fan spin with a battery, a switch and a motor.",
    circuit: "battery B1 p n | slide S1 p a | motor M1 a n",
    checks: ["S1=off -> M1=off", "S1=on -> M1=spin"],
    predict: { q: "What will the motor turn electricity into?", options: ["Light", "Movement", "Sound"], answer: 1, why: "A motor turns electricity into spinning: movement." },
    explain: "Inside the motor, electricity makes a magnet push and pull, so the shaft spins and turns the fan.",
    world: "Fans, toy cars, electric toothbrushes and washing machines all have motors.",
    tryThis: "Count how many things at home have a motor inside.",
    concepts: ["loop", "switch", "energy"] },
  { id: "lab-1-3", unit: 1, level: "explorer", emoji: "🔘", title: "Press to light",
    q: "What's the difference between a switch and a button?", goal: "Light the bulb only while you press a button.",
    circuit: "battery B1 p n | button BTN1 p a | lamp L1 a n",
    checks: ["BTN1=up -> L1=off", "BTN1=down -> L1=on"],
    predict: { q: "You press the button, then let go. What happens to the bulb?", options: ["It stays on", "It goes off when you let go"], answer: 1, why: "A spring pushes the button back up, opening the gap again." },
    explain: "A push button closes the loop only while it's pressed. A slide switch stays where you leave it.",
    world: "Doorbells, keyboard keys and lift buttons are push buttons.",
    tryThis: "Swap the button for the slide switch. Which would you use for a torch, and which for a doorbell?",
    concepts: ["loop", "switch"] },
  { id: "lab-1-4", unit: 1, level: "explorer", emoji: "🔁", title: "Switch on the other side",
    q: "Does it matter where the switch goes in the loop?", goal: "Put the switch between the bulb and the battery's − side.",
    circuit: "battery B1 p n | lamp L1 p a | slide S1 a n",
    checks: ["S1=off -> L1=off", "S1=on -> L1=on"],
    predict: { q: "The switch is now after the bulb. Will it still turn the bulb on and off?", options: ["Yes", "No"], answer: 0, why: "A gap anywhere in the loop stops the electricity, so the switch can go anywhere in it." },
    explain: "There's only one loop. Opening it at any point stops the flow everywhere in it.",
    world: "Electricians put switches wherever is handy in the loop: by the door, at the top of the stairs.",
    tryThis: "Try the switch in three different places in the loop.",
    concepts: ["loop", "switch"] },
  { id: "lab-1-5", unit: 1, level: "explorer", emoji: "🔄", title: "Bulb either way",
    q: "Does a bulb care which way round it goes?", goal: "Turn the battery round and see if the bulb still lights.",
    circuit: "battery B1 n p | slide S1 p a | lamp L1 a n",
    checks: ["S1=on -> L1=on"],
    predict: { q: "The battery is the other way round now. Will the bulb light?", options: ["Yes", "No"], answer: 0, why: "A bulb's thin wire glows whichever way the electricity flows through it." },
    explain: "Electricity now flows round the loop the other way, but a bulb's wire heats up and glows either way.",
    world: "Old torches let you put the batteries in either way… but only some parts don't mind!",
    tryThis: "Remember this one: in Unit 3 you'll meet a light that DOES care which way round it goes.",
    concepts: ["loop", "polarity"] },
  { id: "lab-1-6", unit: 1, level: "explorer", emoji: "↩️", title: "Fan in reverse",
    q: "Can a motor spin backwards?", goal: "Turn the motor round and watch which way the fan spins.",
    circuit: "battery B1 p n | slide S1 p a | motor M1 n a",
    checks: ["S1=on -> M1=reverse"],
    predict: { q: "The motor's wires are swapped. What will the fan do?", options: ["Stop", "Spin the other way", "Spin faster"], answer: 1, why: "Electricity now flows through the motor the other way, so it spins the other way." },
    explain: "A motor spins one way or the other depending on which way the electricity flows through it.",
    world: "Electric windows go up and down, and toy cars drive backwards, by reversing a motor.",
    tryThis: "Does the fan blow air up or down now? Hold a paper strip above it.",
    concepts: ["polarity", "energy"] },
  { id: "lab-1-7", unit: 1, level: "explorer", emoji: "⚠️", title: "Short-circuit detective", safety: true,
    q: "Why is a short circuit dangerous?", goal: "See what happens when a wire skips the bulb (safe here, never with real batteries).",
    circuit: "battery B1 p n | lamp L1 p n | slide S1 p n",
    checks: ["S1=off -> L1=on short=no", "S1=on -> short=yes"],
    predict: { q: "The switch makes a shortcut straight back to the battery. What will happen?", options: ["The bulb gets brighter", "The electricity takes the shortcut and the battery gets hot"], answer: 1, why: "Electricity takes the easiest path. With nothing to hold it back, a huge current flows and heats the battery." },
    explain: "A short circuit is a path with almost no resistance. A real battery can get very hot, leak or even burn. The lab switches off and warns you.",
    world: "Fuses and circuit breakers in homes cut the power when a short circuit happens.",
    tryThis: "Find the shortcut on the board and remove it. Never test this with real batteries!",
    concepts: ["short", "loop"] },
  { id: "lab-1-8", unit: 1, level: "explorer", emoji: "📡", title: "Morse code torch",
    q: "Can a light send a message?", goal: "Build a signalling light and flash SOS: ··· ––– ···",
    circuit: "battery B1 p n | button BTN1 p a | lamp L1 a n",
    checks: ["BTN1=down -> L1=on", "BTN1=up -> L1=off"],
    predict: { q: "Short flashes are dots and long flashes are dashes. Which button suits signalling?", options: ["A push button", "A slide switch"], answer: 0, why: "A push button is quick to press and release, so short and long flashes are easy." },
    explain: "Turning a light on and off in a pattern sends information. Ships used lamps like this to talk at night.",
    world: "Lighthouses, ships and even computers send messages as ON and OFF patterns.",
    tryThis: "Send your name in Morse code to someone across the room.",
    concepts: ["switch", "energy"] },

  // ───────── Unit 2 · Series and parallel ─────────
  { id: "lab-2-1", unit: 2, level: "builder", emoji: "🚂", title: "Lamp and fan in a row",
    q: "What happens when two parts share one loop?", goal: "Put a bulb and a motor in a row (in series).",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a b | motor M1 b n",
    checks: ["S1=on -> L1=dim M1=slow"],
    predict: { q: "The bulb and the fan share the same loop. Will they be as strong as when they were alone?", options: ["Just as strong", "Weaker"], answer: 1, why: "Both parts hold back the electricity, so less flows through the whole loop." },
    explain: "In series, the same electricity goes through every part, one after another. More parts in a row means less current.",
    world: "Some old fairy lights were wired in series: one broken bulb and the whole string went dark.",
    tryThis: "Hold the fan still (in your imagination!): in series, stopping one part affects the other.",
    concepts: ["series", "resistance"] },
  { id: "lab-2-2", unit: 2, level: "builder", emoji: "🛤️", title: "Lamp and fan side by side",
    q: "How can two parts both get full power?", goal: "Put the bulb and the motor side by side (in parallel).",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a n | motor M1 a n",
    checks: ["S1=on -> L1=on M1=spin"],
    predict: { q: "Now each part has its own path to the battery. Bright or dim?", options: ["Bright and fast", "Dim and slow"], answer: 0, why: "In parallel, each part gets the full push of the battery." },
    explain: "In parallel, each part has its own path, so each gets the battery's full voltage.",
    world: "Homes are wired in parallel: every light and socket gets full power on its own.",
    tryThis: "Compare with the series loop: which uses up the battery faster? (Parallel: more current flows.)",
    concepts: ["parallel"] },
  { id: "lab-2-3", unit: 2, level: "builder", emoji: "🎛️", title: "A switch for each",
    q: "How do you control two things separately?", goal: "Give the bulb and the fan a switch each.",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a n | button BTN1 p b | motor M1 b n",
    checks: ["S1=on BTN1=up -> L1=on M1=off", "S1=off BTN1=down -> L1=off M1=spin", "S1=on BTN1=down -> L1=on M1=spin"],
    predict: { q: "The bulb's switch is OFF. Can the fan still spin?", options: ["Yes", "No"], answer: 0, why: "The fan's path doesn't go through the bulb's switch." },
    explain: "Each branch of a parallel circuit can have its own switch, so the parts work on their own.",
    world: "Every room in your home has its own light switch, but they all share the same supply.",
    tryThis: "Add a main switch that turns everything off at once. Where must it go?",
    concepts: ["parallel", "switch"] },
  { id: "lab-2-4", unit: 2, level: "builder", emoji: "⏩", title: "Two-speed fan",
    q: "How can one button make a fan go faster?", goal: "Make the fan slow, and fast while you press the button.",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a b | button BTN1 a b | motor M1 b n",
    checks: ["S1=on BTN1=up -> M1=slow L1=dim", "S1=on BTN1=down -> M1=spin L1=off"],
    predict: { q: "Pressing the button makes a path around the bulb. What happens to the fan?", options: ["It speeds up", "It slows down"], answer: 0, why: "The electricity skips the bulb, so nothing holds it back and the fan gets more." },
    explain: "The bulb holds back some electricity, so the fan is slow. The button makes a bypass around the bulb.",
    world: "Old fan regulators and some toy controllers changed speed by adding or skipping resistance.",
    tryThis: "Does the bulb glow while the button is pressed? Why not?",
    concepts: ["series", "resistance", "switch"] },
  { id: "lab-2-5", unit: 2, level: "builder", emoji: "💡", title: "Two bulbs in a row",
    q: "Do two bulbs in a row shine as brightly as one?", goal: "Light two bulbs in series.",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a b | lamp L2 b n",
    checks: ["S1=on -> L1=dim L2=dim"],
    predict: { q: "Two bulbs share one loop. How bright?", options: ["Both bright", "Both dim"], answer: 1, why: "They share the battery's push, so each gets half." },
    explain: "Two bulbs in series double the resistance, so half as much current flows and both glow dimly.",
    world: "This is why lights in a home are never wired in a row.",
    tryThis: "Unscrew one bulb (remove it from the board). What happens to the other?",
    concepts: ["series", "resistance"] },
  { id: "lab-2-6", unit: 2, level: "builder", emoji: "💡", title: "Two bulbs side by side",
    q: "How do you make two bulbs both shine brightly?", goal: "Light two bulbs in parallel.",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a n | lamp L2 a n",
    checks: ["S1=on -> L1=on L2=on"],
    predict: { q: "Each bulb has its own path. How bright?", options: ["Both bright", "Both dim"], answer: 0, why: "Each bulb gets the full 3 volts." },
    explain: "In parallel each bulb gets the battery's full voltage. The battery works harder, giving twice the current.",
    world: "Car headlights are in parallel: if one fails, the other keeps shining.",
    tryThis: "Remove one bulb now. Does the other stay on?",
    concepts: ["parallel"] },
  { id: "lab-2-7", unit: 2, level: "builder", emoji: "🎪", title: "Light, fan and LED together",
    q: "How many things can one battery run at once?", goal: "Run a bulb, a fan and an LED in parallel from one switch.",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a n | motor M1 a n | resistor R1 a b 100 | led D1 b n red",
    checks: ["S1=off -> L1=off M1=off D1=off", "S1=on -> L1=on M1=spin D1=on"],
    predict: { q: "Will all three work at full strength?", options: ["Yes", "Only one of them"], answer: 0, why: "Each has its own branch, and the battery can supply all three." },
    explain: "Every branch gets 3 volts. The more branches, the more current the battery supplies, and the sooner it runs flat.",
    world: "A power strip runs many things at once in parallel.",
    tryThis: "Which part uses the least electricity? (The LED: that's why LED lights save energy.)",
    concepts: ["parallel", "energy"] },
  { id: "lab-2-8", unit: 2, level: "builder", emoji: "🏠", title: "Master switch",
    q: "How does one switch turn off a whole house?", goal: "Give two lights their own switches, and one main switch for both.",
    circuit: "battery B1 p n | slide S1 p a | slide S2 a b | lamp L1 b n | button BTN1 a c | lamp L2 c n",
    checks: ["S1=off S2=on BTN1=down -> L1=off L2=off", "S1=on S2=on BTN1=up -> L1=on L2=off", "S1=on S2=off BTN1=down -> L1=off L2=on"],
    predict: { q: "The main switch is OFF. Can either light come on?", options: ["Yes", "No"], answer: 1, why: "The main switch is before both branches, so it cuts the power to everything." },
    explain: "The main switch is in series with everything; each light's own switch is in its own branch.",
    world: "The main switch in your home's fuse box works exactly like this.",
    tryThis: "Ask a grown-up to show you your home's main switch (look, don't touch).",
    concepts: ["series", "parallel", "switch"] },

  // ───────── Unit 3 · LEDs and resistors ─────────
  { id: "lab-3-1", unit: 3, level: "builder", emoji: "🔴", title: "Light an LED safely",
    q: "Why does an LED need a resistor?", goal: "Light an LED with a resistor to protect it.",
    circuit: "battery B1 p n | slide S1 p a | resistor R1 a b 100 | led D1 b n red",
    checks: ["S1=off -> D1=off", "S1=on -> D1=on"],
    predict: { q: "What is the resistor for?", options: ["To make the LED brighter", "To stop too much electricity flowing"], answer: 1, why: "An LED lets a lot of current through once it's on; the resistor holds it to a safe amount." },
    explain: "LEDs turn electricity into light very efficiently, but they need a resistor to keep the current safe.",
    world: "Phone screens, traffic lights and TV standby lights are all LEDs.",
    tryThis: "Find three LEDs at home.",
    concepts: ["resistance", "energy"] },
  { id: "lab-3-2", unit: 3, level: "builder", emoji: "↔️", title: "LED one way only",
    q: "Does an LED care which way round it goes?", goal: "Turn the LED round and see what happens.",
    circuit: "battery B1 p n | slide S1 p a | resistor R1 a b 100 | led D1 n b red",
    checks: ["S1=on -> D1=off"],
    predict: { q: "The LED's + is now on the battery's − side. Will it light?", options: ["Yes", "No"], answer: 1, why: "An LED only lets electricity through from + to −." },
    explain: "LED stands for Light Emitting Diode. A diode is a one-way door for electricity.",
    world: "One-way diodes protect gadgets if batteries are put in the wrong way.",
    tryThis: "Turn it back. Remember the bulb in Unit 1, which didn't care!",
    concepts: ["polarity"] },
  { id: "lab-3-3", unit: 3, level: "builder", emoji: "💥", title: "No resistor? Too much!", safety: true,
    q: "What happens to an LED without a resistor?", goal: "See the lab warn you when an LED has no protection (never try this for real).",
    circuit: "battery B1 p n | slide S1 p a | led D1 a n red",
    checks: ["S1=on -> D1=damage"],
    predict: { q: "Nothing holds the current back. What happens?", options: ["The LED glows nicely", "Too much current damages the LED"], answer: 1, why: "Without a resistor, the current rises until the LED overheats." },
    explain: "Real LEDs burn out like this. The lab shows the damage and lets you fix it.",
    world: "Engineers always calculate the right resistor for every LED.",
    tryThis: "Add the 100 Ω resistor back. Now it's safe.",
    concepts: ["resistance", "short"] },
  { id: "lab-3-4", unit: 3, level: "builder", emoji: "🧱", title: "Too much resistance",
    q: "Can a resistor hold back too much?", goal: "Try three resistors and find the one that's too strong.",
    circuit: "battery B1 p n | slide S1 p a | resistor R1 a b 10000 | led D1 b n red",
    checks: ["S1=on -> D1=off"],
    predict: { q: "This resistor is 10 000 Ω (ohms). Will the LED light?", options: ["Brightly", "Not really"], answer: 1, why: "10 kΩ lets through so little current that the LED can't light." },
    explain: "Resistance is measured in ohms (Ω). More ohms, less current. Too many and nothing works.",
    world: "Volume knobs and dimmers change resistance to set how much flows.",
    tryThis: "Swap in 1 kΩ, then 100 Ω. Which is dim, and which is bright?",
    concepts: ["resistance"] },
  { id: "lab-3-5", unit: 3, level: "builder", emoji: "🧭", title: "Battery direction finder",
    q: "How can you tell which way electricity flows?", goal: "Put two LEDs facing opposite ways; only one lights.",
    circuit: "battery B1 p n | slide S1 p a | resistor R1 a b 100 | led D1 b n red | led D2 n b green",
    checks: ["S1=on -> D1=on D2=off"],
    predict: { q: "Two LEDs face opposite ways. Which will light?", options: ["Both", "Only the one pointing from + to −", "Neither"], answer: 1, why: "Each LED lets electricity through one way only." },
    explain: "The LED that lights shows which way the electricity is flowing. Turn the battery round and the other one lights.",
    world: "Testers like this check which wire is + in cars and gadgets.",
    tryThis: "Turn the battery round. Which LED lights now?",
    concepts: ["polarity"] },
  { id: "lab-3-6", unit: 3, level: "builder", emoji: "🚦", title: "Stop and go lights",
    q: "How do traffic lights get their colours?", goal: "Build a red light and a green light, each with its own control.",
    circuit: "battery B1 p n | slide S1 p a | resistor R1 a b 100 | led D1 b n red | button BTN1 p c | resistor R2 c d 100 | led D2 d n green",
    checks: ["S1=on BTN1=up -> D1=on D2=off", "S1=off BTN1=down -> D1=off D2=on"],
    predict: { q: "Does each LED need its own resistor?", options: ["Yes", "No, one is enough"], answer: 0, why: "Each branch carries its own current, so each LED needs its own protection." },
    explain: "Each LED gives one colour. Each branch has its own resistor and its own control.",
    world: "Traffic lights use big clusters of LEDs: they're bright and last for years.",
    tryThis: "Play traffic police: red for stop, green for go.",
    concepts: ["parallel", "resistance"] },
  { id: "lab-3-7", unit: 3, level: "builder", emoji: "🔆", title: "Bright and dim",
    q: "How does resistance change brightness?", goal: "Light two LEDs with different resistors and compare.",
    circuit: "battery B1 p n | slide S1 p a | resistor R1 a b 100 | led D1 b n red | resistor R2 a c 1000 | led D2 c n red",
    checks: ["S1=on -> D1=on D2=dim"],
    predict: { q: "Which LED will be brighter?", options: ["The one with 100 Ω", "The one with 1000 Ω"], answer: 0, why: "Less resistance lets more current through, so it's brighter." },
    explain: "1000 Ω lets through about ten times less current than 100 Ω, so that LED is dimmer.",
    world: "Screens dim at night by letting less current through their lights.",
    tryThis: "Swap the two resistors. Which LED is bright now?",
    concepts: ["resistance"] },
  { id: "lab-3-8", unit: 3, level: "builder", emoji: "🟢", title: "Power-on light",
    q: "How does a gadget show that it's switched on?", goal: "Add an LED that lights whenever the fan is on.",
    circuit: "battery B1 p n | slide S1 p a | motor M1 a n | resistor R1 a b 100 | led D1 b n green",
    checks: ["S1=off -> M1=off D1=off", "S1=on -> M1=spin D1=on"],
    predict: { q: "Where should the LED go so it shows the fan's power?", options: ["Side by side with the fan", "Before the battery"], answer: 0, why: "In parallel with the fan, the LED gets power exactly when the fan does." },
    explain: "An indicator LED in parallel with a part lights whenever that part has power.",
    world: "TVs, chargers and kettles all have a little power-on light.",
    tryThis: "Find three power lights at home. What colours are they?",
    concepts: ["parallel", "energy"] },

  // ───────── Unit 4 · Conductors ─────────
  { id: "lab-4-1", unit: 4, level: "explorer", emoji: "🧪", title: "Conduction tester",
    q: "What lets electricity through?", goal: "Build a tester and try a spoon, an eraser and paper.",
    circuit: "battery B1 p n | probe P1 p a | lamp L1 a n",
    checks: ["P1=spoon -> L1=on", "P1=rubber -> L1=off", "P1=paper -> L1=off"],
    predict: { q: "Which will light the bulb?", options: ["Steel spoon", "Rubber eraser", "Paper"], answer: 0, why: "Metals are conductors: they let electricity flow." },
    explain: "Conductors (like metals) let electricity through. Insulators (like rubber and paper) stop it.",
    world: "Wires are metal inside, covered in plastic to keep us safe.",
    tryThis: "Test a coin, a key and a plastic ruler.",
    concepts: ["conductor"] },
  { id: "lab-4-2", unit: 4, level: "builder", emoji: "🔬", title: "Super-sensitive tester",
    q: "Can we find things that conduct a little?", goal: "Use an LED instead of a bulb to spot weak conductors.",
    circuit: "battery B1 p n | probe P1 p a | resistor R1 a b 100 | led D1 b n red",
    checks: ["P1=coin -> D1=on", "P1=salt -> D1=dim", "P1=plastic -> D1=off"],
    predict: { q: "An LED needs much less electricity than a bulb. Will salty water make it glow?", options: ["Yes, a little", "No"], answer: 0, why: "Salt water conducts a little: enough for an LED, not for a bulb." },
    explain: "An LED lights with a tiny current, so it can show things a bulb can't.",
    world: "Electricians' testers can find very weak paths for electricity.",
    tryThis: "Try the same things in the bulb tester. Which tester is better?",
    concepts: ["conductor", "resistance"] },
  { id: "lab-4-3", unit: 4, level: "builder", emoji: "✏️", title: "Pencil wire",
    q: "Can you draw a wire?", goal: "Test a thick pencil line on paper.",
    circuit: "battery B1 p n | probe P1 p a | resistor R1 a b 100 | led D1 b n red",
    checks: ["P1=pencil -> D1=dim", "P1=paper -> D1=off"],
    predict: { q: "Pencil 'lead' is made of graphite, a kind of carbon. Will it conduct?", options: ["Yes, a little", "No"], answer: 0, why: "Graphite conducts, though not as well as metal." },
    explain: "Graphite is one of the few non-metals that conducts. A thick, dark line works best.",
    world: "Graphite is used in batteries and in the brushes of motors.",
    tryThis: "Draw a short line and a long one. Which makes the LED brighter? (Shorter: less resistance.)",
    concepts: ["conductor", "resistance"] },
  { id: "lab-4-4", unit: 4, level: "explorer", emoji: "💧", title: "Is water a conductor?",
    q: "Does water carry electricity?", goal: "Test tap water with the LED tester.",
    circuit: "battery B1 p n | probe P1 p a | resistor R1 a b 100 | led D1 b n red",
    checks: ["P1=water -> D1=off", "P1=key -> D1=on"],
    predict: { q: "Will tap water light the LED?", options: ["Yes, brightly", "Hardly at all"], answer: 1, why: "Pure water barely conducts; tap water only a tiny bit, too little for the LED." },
    explain: "Tap water conducts only a tiny bit, too little to light the LED. But mains electricity is far stronger: never touch switches with wet hands!",
    world: "That's why bathrooms have special safe switches.",
    tryThis: "Next project: what happens if you add salt?",
    concepts: ["conductor"] },
  { id: "lab-4-5", unit: 4, level: "builder", emoji: "🧂", title: "Salt water",
    q: "Why does salt make water conduct?", goal: "Test salty water and compare with tap water.",
    circuit: "battery B1 p n | probe P1 p a | resistor R1 a b 100 | led D1 b n red",
    checks: ["P1=salt -> D1=dim", "P1=water -> D1=off"],
    predict: { q: "Salt dissolves into tiny charged bits called ions. Will the LED glow now?", options: ["Yes", "No"], answer: 0, why: "Ions carry electricity through the water." },
    explain: "Dissolved salt makes charged particles (ions) that carry the current. Sea water conducts well.",
    world: "Your body is salty water inside, which is why electricity is dangerous to people.",
    tryThis: "More salt, brighter LED? Predict first, then test it in the lab with a pinch and a spoonful.",
    concepts: ["conductor"] },
  { id: "lab-4-6", unit: 4, level: "builder", emoji: "🌊", title: "Water detector",
    q: "How can a chip notice a tiny current?", goal: "Use the melody chip to detect water.",
    circuit: "battery B1 p n | probe P1 p t | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["P1=air -> SPK1=quiet", "P1=water -> SPK1=sound:melody"],
    predict: { q: "Tap water couldn't light the LED. Can it switch on the chip?", options: ["Yes", "No"], answer: 0, why: "The chip's trigger needs only a tiny current, much less than an LED." },
    explain: "Chips can sense very small currents, so even tap water can trigger them.",
    world: "Leak detectors under washing machines work like this.",
    tryThis: "Try a finger in the clips. Your skin conducts a little too!",
    concepts: ["conductor", "chip", "sensor"] },
  { id: "lab-4-7", unit: 4, level: "builder", emoji: "👆", title: "Touch tune",
    q: "Can your finger complete a circuit?", goal: "Play a tune by touching a plate.",
    circuit: "battery B1 p n | touch T1 p t | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["T1=no -> SPK1=quiet", "T1=yes -> SPK1=sound:melody"],
    predict: { q: "Your finger touches both pads of the plate. Will the tune play?", options: ["Yes", "No"], answer: 0, why: "Your body conducts a tiny current, enough for the chip." },
    explain: "Your body is a weak conductor. The current is tiny and perfectly safe with a 3 V battery.",
    world: "Some lamps turn on when you touch their metal base.",
    tryThis: "Hold hands with someone and touch one pad each. Does it still work?",
    concepts: ["conductor", "sensor", "chip"] },
  { id: "lab-4-8", unit: 4, level: "builder", emoji: "🌧️", title: "Rain alarm with lights",
    q: "How can an alarm both flash and sound?", goal: "Make a water alarm that flashes an LED too.",
    circuit: "battery B1 p n | probe P1 p t | siren SIR1 p n t o - - | speaker SPK1 o n | resistor R1 o b 100 | led D1 b n red",
    checks: ["P1=air -> SPK1=quiet D1=off", "P1=water -> SPK1=sound:police D1=flash"],
    predict: { q: "The LED and the speaker both connect to the chip's output. What will the LED do?", options: ["Flash with the siren", "Stay off"], answer: 0, why: "The chip's output switches on and off very fast, and the LED follows it." },
    explain: "One output can drive several things in parallel: here a sound and a light.",
    world: "Fire alarms flash a light as well, so people who can't hear the sound still know.",
    tryThis: "Put the rain alarm 'outside' (on a window sill) and test it with a few drops.",
    concepts: ["conductor", "alarm", "parallel"] },
  { id: "lab-4-9", unit: 4, level: "builder", emoji: "🛸", title: "Touch for space sounds",
    q: "Can a touch change a sound?", goal: "Touch the plate to step through the space sounds.",
    circuit: "battery B1 p n | touch T1 p t | fx FX1 p n t o | speaker SPK1 o n",
    checks: ["T1=no -> SPK1=quiet", "T1=yes -> SPK1=sound:space"],
    predict: { q: "Each touch plays the next sound. How many sounds do you think the chip knows?", options: ["1", "8", "100"], answer: 1, why: "This chip has 8 sounds stored inside, played one after another." },
    explain: "The chip counts each touch and plays the next sound from its memory.",
    world: "Toys with sound buttons have chips like this inside.",
    tryThis: "Touch quickly, then slowly. Can you hear all 8 sounds?",
    concepts: ["chip", "sensor"] },
  { id: "lab-4-10", unit: 4, level: "explorer", emoji: "🗂️", title: "Sort the materials",
    q: "Which things around you are conductors?", goal: "Test six things and sort them into conductors and insulators.",
    circuit: "battery B1 p n | probe P1 p a | resistor R1 a b 100 | led D1 b n red",
    checks: ["P1=spoon -> D1=on", "P1=coin -> D1=on", "P1=foil -> D1=on", "P1=wood -> D1=off", "P1=plastic -> D1=off", "P1=rubber -> D1=off"],
    predict: { q: "What do all the conductors have in common?", options: ["They're all metal", "They're all heavy", "They're all shiny"], answer: 0, why: "Every conductor here is a metal." },
    explain: "Metals conduct; wood, plastic and rubber insulate. Engineers choose materials for each job.",
    world: "A plug: metal pins to carry electricity, plastic case to keep your hand safe.",
    tryThis: "Look at a charger cable: find the conductor and the insulator.",
    concepts: ["conductor"] },
];
