// Circuit Lab projects, units 9–11: alarms, games and inventor briefs. Original projects.
// Games add `game` (what the app does around the circuit). Briefs add `brief` and are judged
// only by their checks: the child designs the circuit; `circuit` is one possible solution.
// `decoys` are parts placed on purpose that don't connect to anything useful.

export const PROJECTS_C = [
  // ───────── Unit 9 · Alarms ─────────
  { id: "lab-9-1", unit: 9, level: "inventor", emoji: "🚪", title: "Door alarm",
    q: "How does an alarm know a door was opened?", goal: "Sound the siren when the door contact opens.",
    circuit: "battery B1 p n | resistor R1 p t 10000 | slide S1 t n | siren SIR1 p n t o - - | speaker SPK1 o n",
    checks: ["S1=on -> SPK1=quiet", "S1=off -> SPK1=sound:police"],
    predict: { q: "The contact is closed while the door is shut. What happens when it opens?", options: ["The alarm sounds", "Nothing"], answer: 0, why: "Closed, it pulls the trigger LOW. Open, the resistor pulls it HIGH." },
    explain: "Alarms usually watch for a loop being BROKEN, so cutting a wire also sets them off.",
    world: "Shop and home alarms have magnetic contacts on doors and windows.",
    tryThis: "Why is 'alarm when the loop breaks' safer than 'alarm when it closes'?",
    concepts: ["alarm", "logic", "switch"] },
  { id: "lab-9-2", unit: 9, level: "builder", emoji: "🧘", title: "Pressure mat",
    q: "How can a doormat play a welcome tune?", goal: "Play a tune when someone steps on the mat.",
    circuit: "battery B1 p n | button BTN1 p t | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["BTN1=up -> SPK1=quiet", "BTN1=down -> SPK1=sound:melody"],
    predict: { q: "What's inside a pressure mat?", options: ["A flat switch that closes when squashed", "A camera"], answer: 0, why: "Two metal sheets with a gap: a foot presses them together." },
    explain: "A pressure mat is a big flat push button.",
    world: "Automatic doors and some shop entrances use pressure mats.",
    tryThis: "Make it a burglar alarm instead: which chip would you use?",
    concepts: ["alarm", "switch", "chip"] },
  { id: "lab-9-3", unit: 9, level: "inventor", emoji: "🧵", title: "Tripwire",
    q: "How does a thin wire guard a room?", goal: "Sound the robot alarm when a foil tripwire breaks.",
    circuit: "battery B1 p n | resistor R1 p t 10000 | probe P1 t n | siren SIR1 p n t o p p | speaker SPK1 o n",
    checks: ["P1=foil -> SPK1=quiet", "P1=air -> SPK1=sound:robot"],
    predict: { q: "Someone walks through and tears the foil. Why does the alarm sound?", options: ["The loop to − is broken", "The foil makes a sound"], answer: 0, why: "Without the foil, the trigger is pulled HIGH." },
    explain: "Same idea as the door alarm: a broken loop sets it off.",
    world: "Museums protect paintings with fine wires and beams.",
    tryThis: "In the lab, 'foil' is the tripwire in place and 'air' is the wire torn.",
    concepts: ["alarm", "conductor", "logic"] },
  { id: "lab-9-4", unit: 9, level: "inventor", emoji: "🪴", title: "Thirsty plant alarm",
    q: "How can a plant ask for water?", goal: "Play a tune when the soil dries out.",
    circuit: "battery B1 p n | resistor R1 p t 10000 | probe P1 t n | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["P1=wetsoil -> SPK1=quiet", "P1=drysoil -> SPK1=sound:melody"],
    predict: { q: "Wet soil conducts; dry soil doesn't. When will the tune play?", options: ["When the soil is wet", "When the soil is dry"], answer: 1, why: "Wet soil pulls the trigger LOW; dry soil lets the resistor pull it HIGH." },
    explain: "Water in the soil carries current. The alarm listens for it stopping.",
    world: "Farms use soil sensors to water crops only when needed, saving water.",
    tryThis: "Would this work in sand? In clay? Why might they differ?",
    concepts: ["alarm", "conductor", "sensor"] },
  { id: "lab-9-5", unit: 9, level: "inventor", emoji: "🔦", title: "Light-beam alarm",
    q: "How does a beam of light catch an intruder?", goal: "Shine the bulb at the sensor; sound the alarm when the beam is broken.",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a n | resistor R1 p t 10000 | ldr LDR1 t n | siren SIR1 p n t o - - | speaker SPK1 o n",
    checks: ["S1=on LDR1=lamp -> L1=on SPK1=quiet", "S1=on LDR1=dark -> SPK1=sound:police"],
    predict: { q: "Someone walks between the bulb and the sensor. What happens?", options: ["The sensor goes dark and the alarm sounds", "The bulb goes out"], answer: 0, why: "The shadow raises the sensor's resistance, so the trigger goes HIGH." },
    explain: "The beam keeps the sensor bright. Break it and the alarm triggers.",
    world: "Lift doors use light beams so they don't close on people.",
    tryThis: "Real beams are often invisible infrared light. Why is that a good idea?",
    concepts: ["alarm", "sensor", "logic"] },
  { id: "lab-9-6", unit: 9, level: "inventor", emoji: "🤫", title: "Silent alarm",
    q: "Why would an alarm be silent?", goal: "Flash an LED instead of making a sound.",
    circuit: "battery B1 p n | button BTN1 p t | siren SIR1 p n t o - - | resistor R1 o b 100 | led D1 b n red",
    checks: ["BTN1=up -> D1=off", "BTN1=down -> D1=flash"],
    predict: { q: "Who might want an alarm with no sound?", options: ["A shop that wants to call for help secretly", "Nobody"], answer: 0, why: "A silent alarm warns helpers without frightening anyone." },
    explain: "Outputs can be lights, sounds or messages. Engineers choose what suits the people using it.",
    world: "Banks have silent alarm buttons; some doorbells flash for people who can't hear.",
    tryThis: "Add the speaker back with a switch to choose 'loud' or 'silent'.",
    concepts: ["alarm", "chip"] },
  { id: "lab-9-7", unit: 9, level: "inventor", emoji: "🚑", title: "Flood alarm",
    q: "How can an alarm warn of rising water?", goal: "Sound the ambulance siren and flash an LED when water reaches the clips.",
    circuit: "battery B1 p n | probe P1 p t | siren SIR1 p n t o - p | speaker SPK1 o n | resistor R1 o b 100 | led D1 b n red",
    checks: ["P1=air -> SPK1=quiet D1=off", "P1=water -> SPK1=sound:ambulance D1=flash"],
    predict: { q: "Where should the clips go to warn early?", options: ["Low down, where water arrives first", "High up"], answer: 0, why: "Water reaches low places first." },
    explain: "Water connects the trigger to +. The siren and LED both follow the output.",
    world: "Basements and boats have flood alarms and pumps that start by themselves.",
    tryThis: "Combine with the silent alarm: what would a boat need?",
    concepts: ["alarm", "conductor", "parallel"] },
  { id: "lab-9-8", unit: 9, level: "inventor", emoji: "🧊", title: "Fridge door alarm",
    q: "How can a fridge remind you to close it?", goal: "Sound the fire siren while the fridge is bright inside.",
    circuit: "battery B1 p n | ldr LDR1 p t | siren SIR1 p n t o p - | speaker SPK1 o n",
    checks: ["LDR1=dark -> SPK1=quiet", "LDR1=bright -> SPK1=sound:fire"],
    predict: { q: "What does the sensor 'see' when the fridge door is open?", options: ["Light", "Darkness"], answer: 0, why: "Room light shines in through the open door." },
    explain: "Light lowers the sensor's resistance and pulls the trigger HIGH.",
    world: "Real fridges beep if the door stays open too long.",
    tryThis: "Real fridges wait a minute before beeping. Which chip has a delay?",
    concepts: ["alarm", "sensor"] },
  { id: "lab-9-9", unit: 9, level: "inventor", emoji: "🖐️", title: "Don't-touch alarm",
    q: "How can an alarm feel a touch?", goal: "Guard a treasure: sound the fire siren when someone touches the plate.",
    circuit: "battery B1 p n | touch T1 p t | siren SIR1 p n t o p - | speaker SPK1 o n",
    checks: ["T1=no -> SPK1=quiet", "T1=yes -> SPK1=sound:fire"],
    predict: { q: "Why does a finger trigger it but a dry leaf doesn't?", options: ["Skin conducts a little; a dry leaf doesn't", "Fingers are heavier"], answer: 0, why: "Your skin is slightly salty and conducts a tiny current." },
    explain: "Touch sensors use your body as part of the circuit.",
    world: "Museums use touch sensors on precious objects.",
    tryThis: "Does it work through a sheet of paper? Why not?",
    concepts: ["alarm", "sensor", "conductor"] },
  { id: "lab-9-10", unit: 9, level: "inventor", emoji: "🗝️", title: "Alarm with an on/off key",
    q: "How do you stop your own alarm going off?", goal: "Add a key switch that turns the door alarm on or off.",
    circuit: "battery B1 p n | slide S1 p a | resistor R1 a t 10000 | slide S2 t n | siren SIR1 a n t o - - | speaker SPK1 o n",
    checks: ["S1=off S2=off -> SPK1=quiet", "S1=on S2=on -> SPK1=quiet", "S1=on S2=off -> SPK1=sound:police"],
    predict: { q: "The key switch is OFF and the door opens. Alarm?", options: ["Yes", "No"], answer: 1, why: "The key switch cuts the alarm's power." },
    explain: "S1 is the key (it powers the alarm); S2 is the door contact. Alarm = key ON AND door NOT closed.",
    world: "Home alarms have a keypad so the owner can switch them off.",
    tryThis: "Add a green LED that shows 'alarm armed'.",
    concepts: ["alarm", "logic", "series"] },

  // ───────── Unit 10 · Games ─────────
  { id: "lab-10-1", unit: 10, level: "builder", emoji: "🌀", title: "Steady hand",
    q: "How steady is your hand?", goal: "Build a buzz-wire game: touching the wire plays a tune.",
    circuit: "battery B1 p n | probe P1 p t | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["P1=air -> SPK1=quiet", "P1=foil -> SPK1=sound:melody"],
    game: "Guide the loop along a wiggly wire on screen. Each touch closes the clips (foil) and plays the tune; fewer touches, more stars.",
    predict: { q: "Why does touching the wire make a sound?", options: ["Metal touching metal closes the loop", "The wire is magic"], answer: 0, why: "The loop and the wire are both metal, so touching joins them." },
    explain: "The wand and the wire are the two sides of a switch. Your hand opens and closes it.",
    world: "Fairground buzz-wire games work exactly like this.",
    tryThis: "Make the wire wigglier for a harder level.",
    concepts: ["conductor", "switch"] },
  { id: "lab-10-2", unit: 10, level: "builder", emoji: "⚡", title: "Reaction race",
    q: "How fast are your reactions?", goal: "Build a button that lights an LED and plays a tune.",
    circuit: "battery B1 p n | button BTN1 p t | melody MEL1 p n t o | speaker SPK1 o n | resistor R1 t b 100 | led D1 b n green",
    checks: ["BTN1=up -> D1=off SPK1=quiet", "BTN1=down -> D1=on SPK1=sound:melody"],
    game: "The screen says GO after a random wait; press your button as fast as you can. The app times you in milliseconds.",
    predict: { q: "Most people react in about…", options: ["0.25 seconds", "3 seconds"], answer: 0, why: "Eyes to brain to finger takes about a quarter of a second." },
    explain: "Electricity is almost instant; your nerves are slower. The circuit is far faster than you!",
    world: "Racing drivers and goalkeepers train their reaction times.",
    tryThis: "Is your reaction faster to a sound or a light? Test both!",
    concepts: ["switch", "chip"] },
  { id: "lab-10-3", unit: 10, level: "builder", emoji: "🤐", title: "Quiet zone",
    q: "Can you stay silent?", goal: "Build a noise detector: any loud sound sets it off.",
    circuit: "battery B1 p n | piezo PZ1 t n | fx FX1 p n t o | speaker SPK1 o n",
    checks: ["PZ1=quiet -> SPK1=quiet", "PZ1=clap -> SPK1=sound:space"],
    game: "Stay quiet for 30 seconds (the app counts down). If the microphone or clap button triggers it, try again.",
    predict: { q: "What could set it off besides a clap?", options: ["A loud voice or a bang", "Only claps"], answer: 0, why: "Any sound that shakes the disc enough triggers it." },
    explain: "The buzzer disc senses vibration, so loud sounds of any kind trigger it.",
    world: "Libraries and recording studios use sound meters to keep things quiet.",
    tryThis: "How long can your family stay quiet?",
    concepts: ["sensor", "sound"] },
  { id: "lab-10-4", unit: 10, level: "builder", emoji: "🙋", title: "Quiz buzzers",
    q: "Who pressed first?", goal: "Build two buttons with an LED each for a two-player quiz.",
    circuit: "battery B1 p n | button BTN1 p a | resistor R1 a b 100 | led D1 b n red | button BTN2 p c | resistor R2 c d 100 | led D2 d n green",
    checks: ["BTN1=down BTN2=up -> D1=on D2=off", "BTN1=up BTN2=down -> D1=off D2=on"],
    game: "The app asks a question; the first player to press lights their LED and gets to answer.",
    predict: { q: "Why does each player need a separate branch?", options: ["So each button lights only its own LED", "To make it louder"], answer: 0, why: "Separate parallel branches keep the players apart." },
    explain: "Two parallel branches, each with its own button, resistor and LED.",
    world: "TV quiz shows use buzzers like these, with a chip that decides who was first.",
    tryThis: "Ask a grown-up five questions. Who wins?",
    concepts: ["parallel", "switch"] },
  { id: "lab-10-5", unit: 10, level: "builder", emoji: "🗺️", title: "Treasure hunt",
    q: "Which switch is the real one?", goal: "Wire three switches, but only one plays the treasure tune.",
    circuit: "battery B1 p n | button BTN1 p t | button BTN2 p x | slide S1 p y | melody MEL1 p n t o | speaker SPK1 o n",
    decoys: ["BTN2", "S1"],
    checks: ["BTN1=down -> SPK1=sound:melody", "BTN2=down -> SPK1=quiet", "S1=on -> SPK1=quiet"],
    game: "A friend builds it hiding which switch is wired; you test switches and follow the wires to find the treasure.",
    predict: { q: "How can you find the real switch without pressing?", options: ["Follow its wire to the chip", "Guess"], answer: 0, why: "Only one switch has a path to the trigger." },
    explain: "Tracing wires is how engineers understand circuits. The decoy switches go nowhere.",
    world: "Electricians trace wires to find which switch controls which light.",
    tryThis: "Make it harder: add longer wires that cross each other.",
    concepts: ["loop", "switch"] },
  { id: "lab-10-6", unit: 10, level: "builder", emoji: "🧠", title: "Copy the lights",
    q: "Can you remember a pattern?", goal: "Build three lights, each with its own control.",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a n | button BTN1 p b | resistor R1 b c 100 | led D1 c n red | button BTN2 p d | resistor R2 d e 100 | led D2 e n green",
    checks: ["S1=on BTN1=up BTN2=up -> L1=on D1=off D2=off", "S1=off BTN1=down BTN2=up -> D1=on", "S1=off BTN1=up BTN2=down -> D2=on"],
    game: "The app shows a pattern of lights; copy it with your switches. The pattern grows by one each round.",
    predict: { q: "Each light has its own control. What kind of circuit is this?", options: ["Parallel", "Series"], answer: 0, why: "Three separate branches from the battery." },
    explain: "Three parallel branches, three independent lights.",
    world: "Memory games train your working memory, like remembering a phone number.",
    tryThis: "How long a pattern can you remember?",
    concepts: ["parallel"] },
  { id: "lab-10-7", unit: 10, level: "builder", emoji: "📟", title: "Morse beeper",
    q: "How did people send messages before phones?", goal: "Send Morse code with beeps.",
    circuit: "battery B1 p n | button BTN1 p t | siren SIR1 p n t o p p | speaker SPK1 o n",
    checks: ["BTN1=up -> SPK1=quiet", "BTN1=down -> SPK1=sound:robot"],
    game: "The app shows a word; beep it in Morse code. It listens to your presses and decodes them.",
    predict: { q: "Why does a siren chip suit Morse?", options: ["It sounds only while the trigger is held", "It plays a tune"], answer: 0, why: "Short press, short beep; long press, long beep." },
    explain: "The siren sounds only while its trigger is HIGH, so it follows your button exactly.",
    world: "Telegraphs sent Morse code along wires across whole continents.",
    tryThis: "Send SOS: ··· ––– ···",
    concepts: ["switch", "chip", "sound"] },
  { id: "lab-10-8", unit: 10, level: "builder", emoji: "⚽", title: "Fan football",
    q: "Can air score a goal?", goal: "Use the fan to blow a paper ball into a goal.",
    circuit: "battery B1 p n | button BTN1 p a | motor M1 a n",
    checks: ["BTN1=down -> M1=spin", "BTN1=up -> M1=off"],
    game: "A paper ball sits on the screen; hold the button to blow it. Short bursts aim better!",
    predict: { q: "Which way does the fan push the air?", options: ["Away from the blades' tilt", "Nowhere"], answer: 0, why: "Tilted blades push air in one direction." },
    explain: "The spinning fan moves air, which pushes the ball.",
    world: "Hovercraft and air-hockey tables use moving air.",
    tryThis: "Play against a friend: one goal each side.",
    concepts: ["energy"] },

  // ───────── Unit 11 · Inventor briefs ─────────
  { id: "lab-11-1", unit: 11, level: "engineer", emoji: "👶", title: "Baby's night light",
    q: "Can you design a light that comes on by itself at bedtime?",
    brief: "A parent wants a small light that switches on when the room gets dark and off when it's light, with no switch to press.",
    goal: "Design a circuit: LED on in the dark, off in the light.",
    circuit: "battery B1 p n | resistor R1 p b 10000 | ldr LDR1 b n | resistor R2 p c 100 | led D1 c d yellow | transistor Q1 d b n",
    checks: ["LDR1=bright -> D1=off", "LDR1=dark -> D1=on"],
    predict: { q: "Which part can switch a light on when something else turns OFF?", options: ["A transistor with a pull-up resistor", "A slide switch"], answer: 0, why: "The sensor pulls the base down in light; in the dark the resistor pulls it up." },
    explain: "Your design is judged by what it does, not how it looks. Any circuit that passes the checks is a good solution.",
    world: "Product designers start from a person's need, then design the circuit.",
    tryThis: "Make it softer: which resistor would dim the LED?",
    concepts: ["design", "sensor", "transistor"] },
  { id: "lab-11-2", unit: 11, level: "inventor", emoji: "🚲", title: "Bike indicators",
    q: "Can you design turn signals for a bike?",
    brief: "A cyclist wants a left light and a right light, chosen with one switch, so drivers know which way they're turning.",
    goal: "One two-way switch: up lights the left LED, down lights the right LED.",
    circuit: "battery B1 p n | changeover SW1 p a b | resistor R1 a c 100 | led D1 c n yellow | resistor R2 b d 100 | led D2 d n yellow",
    checks: ["SW1=up -> D1=on D2=off", "SW1=down -> D1=off D2=on"],
    predict: { q: "Why a two-way switch, not two buttons?", options: ["It can never light both at once", "It's cheaper"], answer: 0, why: "A changeover joins its middle to one side or the other, never both." },
    explain: "Choosing the right switch prevents mistakes. That's good design.",
    world: "Cars use a lever with three positions: left, off and right.",
    tryThis: "Add a third position for 'off'. What part would you need?",
    concepts: ["design", "switch", "parallel"] },
  { id: "lab-11-3", unit: 11, level: "inventor", emoji: "🗼", title: "Lighthouse",
    q: "Can you design a lighthouse that works on its own at night?",
    brief: "A tiny island needs a lighthouse that flashes and sounds a foghorn when it gets dark.",
    goal: "When it's dark: LED flashes and the speaker sounds. In daylight: nothing.",
    circuit: "battery B1 p n | resistor R1 p t 10000 | ldr LDR1 t n | siren SIR1 p n t o - - | speaker SPK1 o n | resistor R2 o b 100 | led D1 b n yellow",
    checks: ["LDR1=bright -> SPK1=quiet D1=off", "LDR1=dark -> SPK1=sound D1=flash"],
    predict: { q: "Which trick from Unit 9 makes something happen in the DARK?", options: ["Pull-up resistor + sensor to −", "Two batteries"], answer: 0, why: "Dark sensor stops pulling the trigger down, so the resistor pulls it up." },
    explain: "Combine a dark-sensing trigger with a chip that drives a light and a sound.",
    world: "Real lighthouses switch on automatically at dusk.",
    tryThis: "Which siren sound makes the best foghorn?",
    concepts: ["design", "sensor", "alarm"] },
  { id: "lab-11-4", unit: 11, level: "inventor", emoji: "🛎️", title: "Shop door chime",
    q: "Can you design a chime that rings when a customer walks in?",
    brief: "A shopkeeper at the back of the shop wants a tune to play whenever someone walks through the door, breaking a light beam.",
    goal: "Light beam across the door: a tune plays when the beam is broken.",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a n | resistor R1 p t 10000 | ldr LDR1 t n | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["S1=on LDR1=lamp -> SPK1=quiet", "S1=on LDR1=dark -> SPK1=sound:melody", "S1=off LDR1=lamp -> SPK1=sound:melody"],
    predict: { q: "Why a melody chip instead of a siren?", options: ["A friendly tune suits customers", "Sirens can't be triggered"], answer: 0, why: "Design for the people using it: a tune welcomes, a siren alarms." },
    explain: "Same beam idea as the alarm, but a friendlier output. Who uses it changes the design.",
    world: "Many shops have chimes or bells that ring when the door opens.",
    tryThis: "Should it also count customers? What would that need?",
    concepts: ["design", "sensor", "chip"] },
  { id: "lab-11-5", unit: 11, level: "inventor", emoji: "🔒", title: "Secret code lock",
    q: "Can you design a lock with a trap?",
    brief: "Design a treasure box lock: two switches must be ON, and a trap button must NOT be pressed, to play the 'unlocked' tune.",
    goal: "Tune plays only for: switch 1 ON, switch 2 ON, trap button not pressed.",
    circuit: "battery B1 p n | slide S1 p a | slide S2 a b | resistor R1 b t 10000 | button BTN1 t n | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["S1=on S2=on BTN1=up -> SPK1=sound:melody", "S1=on S2=on BTN1=down -> SPK1=quiet", "S1=on S2=off BTN1=up -> SPK1=quiet", "S1=off S2=on BTN1=up -> SPK1=quiet"],
    predict: { q: "This lock is S1 AND S2 AND NOT trap. How many of the 8 combinations open it?", options: ["1", "3", "8"], answer: 0, why: "Only ON, ON, not pressed." },
    explain: "Logic in a row (AND) plus a pull-down button (NOT) makes a combination lock.",
    world: "Digital locks combine many conditions in a chip.",
    tryThis: "Design a lock with a different secret combination.",
    concepts: ["design", "logic"] },
  { id: "lab-11-6", unit: 11, level: "engineer", emoji: "☀️", title: "Sunny-day fan",
    q: "Can you design a fan that switches on when the sun shines?",
    brief: "A greenhouse gets hot when the sun shines. Design a fan that runs in bright light and stops when it's dark.",
    goal: "Motor spins in bright light, stops in the dark.",
    circuit: "battery B1 p n | ldr LDR1 p b | motor M1 p c | transistor Q1 c b n",
    checks: ["LDR1=bright -> M1=spin", "LDR1=dark -> M1=off"],
    predict: { q: "The motor needs much more current than the sensor can give. What helps?", options: ["A transistor", "A longer wire"], answer: 0, why: "A small current into the base lets a big current flow through the motor." },
    explain: "A transistor amplifies: the sensor controls it with a tiny current, and it controls the motor.",
    world: "Greenhouses, attics and solar gadgets switch fans automatically.",
    tryThis: "What should happen on a cloudy day? Try dim light.",
    deeper: "Bright: about 22 mA flows into the base through the sensor (100 Ω), so the transistor switches fully on. Dark: 1 MΩ lets only about 2 µA in, so it stays off.",
    concepts: ["design", "sensor", "transistor"] },
  { id: "lab-11-7", unit: 11, level: "inventor", emoji: "👀", title: "Doorbell you can see",
    q: "Can you design a doorbell for someone who can't hear?",
    brief: "Design a doorbell that plays a tune AND flashes a light, so everyone in the home knows someone is at the door.",
    goal: "Pressing the button plays a tune and flashes an LED.",
    circuit: "battery B1 p n | button BTN1 p t | melody MEL1 p n t o | speaker SPK1 o n | resistor R1 o b 100 | led D1 b n green",
    checks: ["BTN1=up -> SPK1=quiet D1=off", "BTN1=down -> SPK1=sound:melody D1=flash"],
    predict: { q: "Who else might find a flashing doorbell useful?", options: ["Someone wearing headphones", "Nobody"], answer: 0, why: "Designing for one group often helps many others too." },
    explain: "Inclusive design: thinking about everyone who'll use something.",
    world: "Phones flash, vibrate and ring, so everyone can notice them.",
    tryThis: "Could it also vibrate? Which part could do that? (Hint: a motor with a weight.)",
    concepts: ["design", "chip", "parallel"] },
  { id: "lab-11-8", unit: 11, level: "inventor", emoji: "🛠️", title: "Your own invention", open: true,
    q: "What problem would YOU solve with a circuit?",
    brief: "Think of a problem at home or school. Design a circuit with at least one input (switch, button or sensor) that controls at least one output (light, motor or sound).",
    goal: "Any working design: an input that changes an output.",
    checks: [],
    predict: { q: "What should an engineer do first?", options: ["Ask who it's for and what they need", "Start snapping parts together"], answer: 0, why: "The design cycle starts with asking: Ask, Imagine, Plan, Build, Test, Improve." },
    explain: "Name it, describe the problem, build it, test it and write in your engineer's notebook what you'd improve.",
    world: "Every invention started with someone noticing a problem.",
    tryThis: "Show your invention to your family and ask for one improvement.",
    concepts: ["design"] },
];
