// Circuit Lab projects, units 5–8: motion, sound, sensors and logic. Original projects.

export const PROJECTS_B = [
  // ───────── Unit 5 · Motion ─────────
  { id: "lab-5-1", unit: 5, level: "builder", emoji: "🚁", title: "Launch the fan", safety: true,
    q: "How does a spinning fan fly?", goal: "Spin the fan up with a button, then let go to launch it.",
    circuit: "battery B1 p n | button BTN1 p a | motor M1 a n",
    checks: ["BTN1=down -> M1=spin", "BTN1=up -> M1=off"],
    predict: { q: "Why does the spinning fan rise when you let go?", options: ["Its tilted blades push air down", "Magnets lift it"], answer: 0, why: "The blades are tilted, so spinning pushes air down, and the air pushes the fan up." },
    explain: "Pushing air down pushes the fan up. Helicopter blades and drones work the same way.",
    world: "Helicopters, drones and sycamore seeds all fly by spinning.",
    tryThis: "Hold it longer before letting go. Does it fly higher? (In real life: never launch it at people's faces.)",
    concepts: ["energy"] },
  { id: "lab-5-2", unit: 5, level: "builder", emoji: "🪶", title: "A gentle launch",
    q: "How can you make the fan fly lower?", goal: "Add a bulb in series to slow the motor.",
    circuit: "battery B1 p n | button BTN1 p a | lamp L1 a b | motor M1 b n",
    checks: ["BTN1=down -> M1=slow L1=dim"],
    predict: { q: "With the bulb in the loop, will the fan fly higher or lower?", options: ["Higher", "Lower"], answer: 1, why: "The bulb holds back some electricity, so the fan spins slower and pushes less air." },
    explain: "Less current means a slower motor, less lift and a lower flight.",
    world: "Drones fly up, hover or land by changing their motors' speed.",
    tryThis: "Can you find a way to make it hover? (Hint: speed in between.)",
    concepts: ["series", "resistance", "energy"] },
  { id: "lab-5-3", unit: 5, level: "builder", emoji: "⬇️", title: "Fan that won't fly",
    q: "Why won't the fan fly backwards?", goal: "Reverse the motor and try to launch.",
    circuit: "battery B1 p n | button BTN1 p a | motor M1 n a",
    checks: ["BTN1=down -> M1=reverse"],
    predict: { q: "The fan spins the other way. Will it still fly?", options: ["Yes", "No, it pushes itself down"], answer: 1, why: "Spinning backwards pushes air up, so the fan presses itself down onto the motor." },
    explain: "Changing the direction of spin changes the direction of the push.",
    world: "Planes reverse the thrust of their engines to help them stop after landing.",
    tryThis: "Hold a paper strip above the fan both ways round. Which way does the air go?",
    concepts: ["polarity", "energy"] },
  { id: "lab-5-4", unit: 5, level: "builder", emoji: "🎨", title: "Spin art",
    q: "What pattern does a spinning brush make?", goal: "Spin a paper disc on the motor and 'paint' on it.",
    circuit: "battery B1 p n | slide S1 p a | motor M1 a n",
    checks: ["S1=on -> M1=spin"],
    predict: { q: "You touch a pen to a spinning disc. What shape will it draw?", options: ["A circle", "A straight line"], answer: 0, why: "Every point of the disc goes round in a circle." },
    explain: "The motor turns electricity into steady spinning, perfect for drawing circles and spirals.",
    world: "Potters' wheels and record players spin things the same way.",
    tryThis: "Move the pen slowly from the middle outwards. What do you get? (A spiral!)",
    concepts: ["energy"] },
  { id: "lab-5-5", unit: 5, level: "builder", emoji: "🌈", title: "Spinning colours",
    q: "What colour do you see when colours spin fast?", goal: "Spin a disc of colours at two speeds.",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a b | button BTN1 a b | motor M1 b n",
    checks: ["S1=on BTN1=up -> M1=slow", "S1=on BTN1=down -> M1=spin"],
    predict: { q: "A disc with red, green and blue spins very fast. What do you see?", options: ["Stripes", "Almost white", "Black"], answer: 1, why: "Your eyes blend the colours together when they move too fast to see." },
    explain: "Your eyes keep each picture for a moment, so fast-spinning colours mix together.",
    world: "Screens make every colour by mixing tiny red, green and blue lights.",
    tryThis: "Try two colours: yellow and blue. What do they blend into?",
    concepts: ["energy", "series"] },
  { id: "lab-5-6", unit: 5, level: "builder", emoji: "🎶", title: "Fan with music",
    q: "Can one switch start two things?", goal: "Start the fan and a tune with one switch.",
    circuit: "battery B1 p n | slide S1 p a | motor M1 a n | melody MEL1 a n a o | speaker SPK1 o n",
    checks: ["S1=off -> M1=off SPK1=quiet", "S1=on -> M1=spin SPK1=sound:melody"],
    predict: { q: "The chip's trigger is joined to its own +. When will it play?", options: ["Whenever it has power", "Never"], answer: 0, why: "Its trigger is always HIGH, so it plays all the time it's powered." },
    explain: "The fan and the chip are in parallel after the switch, so one switch controls both.",
    world: "Musical toy carousels play a tune while they turn.",
    tryThis: "Can you change it so the tune only plays while you press a button?",
    concepts: ["parallel", "chip", "sound"] },
  { id: "lab-5-7", unit: 5, level: "builder", emoji: "🚒", title: "Fan with a siren",
    q: "How do you build a toy fire engine?", goal: "Spin the motor and sound a siren together.",
    circuit: "battery B1 p n | slide S1 p a | motor M1 a n | siren SIR1 a n a o a - | speaker SPK1 o n",
    checks: ["S1=on -> M1=spin SPK1=sound:fire"],
    predict: { q: "The siren's mode pin m1 is joined to +. Which siren will it play?", options: ["Police", "Fire engine"], answer: 1, why: "m1 to + selects the fire engine sound." },
    explain: "Chips have extra pins that choose what they do. Here m1 picks the fire engine siren.",
    world: "Toy vehicles use one chip with several sounds, picked by tiny switches.",
    tryThis: "Move the m1 wire to m2. Which siren is that?",
    concepts: ["chip", "sound", "parallel"] },
  { id: "lab-5-8", unit: 5, level: "inventor", emoji: "📸", title: "Strobe light",
    q: "Can a flashing light freeze motion?", goal: "Flash an LED fast while the fan spins.",
    circuit: "battery B1 p n | slide S1 p a | motor M1 a n | fx FX1 a n a o | resistor R1 o b 100 | led D1 b n green",
    checks: ["S1=on -> M1=spin D1=flash"],
    predict: { q: "If a light flashes exactly as fast as the fan turns, how will the fan look?", options: ["Still", "Blurry"], answer: 0, why: "Each flash shows the blade in the same place, so it looks frozen." },
    explain: "A strobe shows quick snapshots. When they match the spin, the blade seems to stand still.",
    world: "Mechanics use strobe lights to check spinning engine parts.",
    tryThis: "In videos, car wheels sometimes look like they spin backwards. That's the same trick!",
    concepts: ["chip", "energy"] },

  // ───────── Unit 6 · Sound ─────────
  { id: "lab-6-1", unit: 6, level: "explorer", emoji: "🔔", title: "Doorbell tune",
    q: "How does a musical doorbell work?", goal: "Play a tune while a button is pressed.",
    circuit: "battery B1 p n | button BTN1 p t | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["BTN1=up -> SPK1=quiet", "BTN1=down -> SPK1=sound:melody"],
    predict: { q: "The chip has power all the time. What does the button do?", options: ["Tells the chip to play", "Powers the speaker directly"], answer: 0, why: "The button connects the trigger to +, which tells the chip to play." },
    explain: "The melody chip stores a tune. A signal on its trigger pin starts it; the speaker turns it into sound.",
    world: "Musical doorbells, greeting cards and toys have tiny melody chips.",
    tryThis: "Press and let go quickly. Does the tune finish anyway?",
    concepts: ["chip", "sound", "switch"] },
  { id: "lab-6-2", unit: 6, level: "explorer", emoji: "🎼", title: "Music box",
    q: "How do you make music play non-stop?", goal: "Keep the tune playing with a slide switch.",
    circuit: "battery B1 p n | slide S1 p t | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["S1=off -> SPK1=quiet", "S1=on -> SPK1=sound:melody"],
    predict: { q: "The slide switch stays ON. What will the chip do?", options: ["Play once", "Play again and again"], answer: 1, why: "While its trigger stays HIGH, the chip starts the tune again each time it ends." },
    explain: "A held trigger keeps the chip playing.",
    world: "Music boxes and toy pianos with a 'demo' button keep playing on their own.",
    tryThis: "Which is better for a doorbell: a button or a slide switch? Why?",
    concepts: ["chip", "sound"] },
  { id: "lab-6-3", unit: 6, level: "explorer", emoji: "🚓", title: "Police siren",
    q: "How is a siren sound made?", goal: "Make the siren chip play a police siren.",
    circuit: "battery B1 p n | slide S1 p a | siren SIR1 a n a o - - | speaker SPK1 o n",
    checks: ["S1=off -> SPK1=quiet", "S1=on -> SPK1=sound:police"],
    predict: { q: "A siren goes up and down. What is changing?", options: ["How high the note is (pitch)", "How heavy the speaker is"], answer: 0, why: "The chip makes the speaker vibrate faster and slower, so the note goes up and down." },
    explain: "Fast vibrations make high notes; slow ones make low notes. The chip sweeps between them.",
    world: "Sirens are designed to grab attention and be heard through traffic.",
    tryThis: "Notice the mode pins m1 and m2 are not connected. Next projects use them!",
    concepts: ["chip", "sound"] },
  { id: "lab-6-4", unit: 6, level: "explorer", emoji: "🚒", title: "Fire engine siren",
    q: "How can one chip make different sirens?", goal: "Connect mode pin m1 to + for the fire engine sound.",
    circuit: "battery B1 p n | slide S1 p a | siren SIR1 a n a o a - | speaker SPK1 o n",
    checks: ["S1=on -> SPK1=sound:fire"],
    predict: { q: "What does connecting m1 to + do?", options: ["Chooses a different sound", "Makes it louder"], answer: 0, why: "Mode pins tell the chip which of its stored sounds to play." },
    explain: "A chip can follow different instructions depending on its mode pins.",
    world: "Many gadgets have settings chosen by tiny switches on a chip's pins.",
    tryThis: "Describe the difference between the police and fire sounds.",
    concepts: ["chip", "sound"] },
  { id: "lab-6-5", unit: 6, level: "explorer", emoji: "🚑", title: "Ambulance siren",
    q: "Why do emergency vehicles sound different?", goal: "Connect mode pin m2 to + for the ambulance sound.",
    circuit: "battery B1 p n | slide S1 p a | siren SIR1 a n a o - a | speaker SPK1 o n",
    checks: ["S1=on -> SPK1=sound:ambulance"],
    predict: { q: "Why might an ambulance sound different from a police car?", options: ["So people know which one is coming", "No reason"], answer: 0, why: "Different sounds tell people what kind of help is coming." },
    explain: "m2 to + picks the two-tone ambulance sound.",
    world: "Countries have their own siren sounds. Which ones have you heard?",
    tryThis: "Can you make the siren chip switch sounds with the push button?",
    concepts: ["chip", "sound"] },
  { id: "lab-6-6", unit: 6, level: "builder", emoji: "🤖", title: "Robot alarm",
    q: "What do two mode pins together do?", goal: "Connect m1 and m2 to + for the robot alarm.",
    circuit: "battery B1 p n | slide S1 p a | siren SIR1 a n a o a a | speaker SPK1 o n",
    checks: ["S1=on -> SPK1=sound:robot"],
    predict: { q: "Two pins, each ON or OFF. How many different sounds can they choose?", options: ["2", "3", "4"], answer: 2, why: "OFF-OFF, ON-OFF, OFF-ON and ON-ON: 4 combinations, like 2 binary lamps!" },
    explain: "Two pins make 4 combinations, so the chip has 4 sounds. That's binary at work.",
    world: "Computers use the same idea: more pins, many more choices.",
    tryThis: "Make a table of the 4 combinations and their sounds.",
    concepts: ["chip", "sound", "logic"] },
  { id: "lab-6-7", unit: 6, level: "explorer", emoji: "👾", title: "Space sounds",
    q: "How does a toy play different sounds?", goal: "Press the button to step through 8 space sounds.",
    circuit: "battery B1 p n | button BTN1 p t | fx FX1 p n t o | speaker SPK1 o n",
    checks: ["BTN1=up -> SPK1=quiet", "BTN1=down -> SPK1=sound:space"],
    predict: { q: "You press the button again. What will you hear?", options: ["The same sound", "The next sound"], answer: 1, why: "The chip counts the presses and plays the next sound each time." },
    explain: "The sound-effects chip keeps count and plays its 8 sounds in turn.",
    world: "Arcade games and toy robots use chips like this.",
    tryThis: "Hold the button down. What happens?",
    concepts: ["chip", "sound"] },
  { id: "lab-6-8", unit: 6, level: "builder", emoji: "🥁", title: "Buzzer disc speaker",
    q: "Can a tiny disc make sound?", goal: "Play the tune through the buzzer disc instead of the speaker.",
    circuit: "battery B1 p n | button BTN1 p t | melody MEL1 p n t o | piezo PZ1 o n",
    checks: ["BTN1=down -> PZ1=sound"],
    predict: { q: "Will the disc be louder or quieter than the speaker?", options: ["Louder", "Quieter"], answer: 1, why: "The disc is small and stiff, so it moves less air." },
    explain: "The disc bends a tiny bit each time electricity reaches it, making a click. Thousands of clicks make a note.",
    world: "Watches, microwaves and smoke alarms beep with buzzer discs.",
    tryThis: "Listen closely: does it sound different from the speaker?",
    concepts: ["sound", "energy"] },
  { id: "lab-6-9", unit: 6, level: "builder", emoji: "🪩", title: "Music and lights",
    q: "Can lights dance to music?", goal: "Make an LED flash in time with the tune.",
    circuit: "battery B1 p n | slide S1 p t | melody MEL1 p n t o | speaker SPK1 o n | resistor R1 o b 100 | led D1 b n green",
    checks: ["S1=on -> SPK1=sound:melody D1=flash"],
    predict: { q: "The LED connects to the same output as the speaker. What will it do?", options: ["Flash with the music", "Stay on steadily"], answer: 0, why: "The output turns on and off with the notes, so the LED does too." },
    explain: "The speaker and the LED share the chip's output, so they follow the same signal.",
    world: "Disco lights and music visualisers react to sound.",
    tryThis: "Swap the green LED for a red one. Use a resistor every time!",
    concepts: ["chip", "sound", "parallel"] },
  { id: "lab-6-10", unit: 6, level: "builder", emoji: "🔉", title: "Volume down",
    q: "How do you make a speaker quieter?", goal: "Add a resistor to the speaker, with a button to skip it.",
    circuit: "battery B1 p n | slide S1 p t | melody MEL1 p n t o | resistor R1 o b 100 | button BTN1 o b | speaker SPK1 b n",
    checks: ["S1=on BTN1=up -> SPK1=soft", "S1=on BTN1=down -> SPK1=sound"],
    predict: { q: "The resistor holds back current to the speaker. Louder or quieter?", options: ["Louder", "Quieter"], answer: 1, why: "Less current makes smaller vibrations: a quieter sound." },
    explain: "Volume is about how much current reaches the speaker. Resistance turns it down.",
    world: "Volume controls change resistance or the strength of a signal.",
    tryThis: "Try the 1 kΩ resistor. Can you still hear it?",
    concepts: ["resistance", "sound"] },
  { id: "lab-6-11", unit: 6, level: "inventor", emoji: "🎭", title: "Two-chip duet",
    q: "What happens when two chips share a speaker?", goal: "Play the melody and the siren together.",
    circuit: "battery B1 p n | slide S1 p t | melody MEL1 p n t o | siren SIR1 p n t o - - | speaker SPK1 o n",
    checks: ["S1=on -> SPK1=sound:mix"],
    predict: { q: "Both chips send their signals to one speaker. What will you hear?", options: ["Only one of them", "Both mixed together"], answer: 1, why: "The speaker follows both signals at once, mixing them." },
    explain: "Signals add up. Mixing is how music studios combine instruments.",
    world: "Your headphones play voices, music and effects mixed into one signal.",
    tryThis: "Is it music or noise? Try separate speakers in your next design.",
    concepts: ["chip", "sound"] },
  { id: "lab-6-12", unit: 6, level: "builder", emoji: "🚪", title: "Two-door doorbell",
    q: "How can two buttons ring one bell?", goal: "Ring the tune from a front button or a back button.",
    circuit: "battery B1 p n | button BTN1 p t | button BTN2 p t | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["BTN1=up BTN2=up -> SPK1=quiet", "BTN1=down BTN2=up -> SPK1=sound:melody", "BTN1=up BTN2=down -> SPK1=sound:melody"],
    predict: { q: "The buttons are side by side. Does the bell need both pressed?", options: ["Yes, both", "No, either one"], answer: 1, why: "Each button makes its own path to the trigger: that's OR." },
    explain: "Buttons in parallel make an OR: either one works. You'll meet OR again in Unit 8.",
    world: "Homes with two doors, and buses with many stop buttons, use OR.",
    tryThis: "Remember Volt's doorbell mission? This is the same idea with a chip.",
    concepts: ["parallel", "logic", "chip"] },

  // ───────── Unit 7 · Sensors ─────────
  { id: "lab-7-1", unit: 7, level: "builder", emoji: "🌗", title: "Light-controlled LED",
    q: "Can a circuit notice light?", goal: "Make an LED that's bright in light and off in the dark.",
    circuit: "battery B1 p n | slide S1 p a | ldr LDR1 a b | led D1 b n red",
    checks: ["S1=on LDR1=bright -> D1=on", "S1=on LDR1=dark -> D1=off"],
    predict: { q: "You cover the light sensor with your hand. What happens to the LED?", options: ["Brighter", "Dimmer or off"], answer: 1, why: "In the dark, the sensor's resistance goes up and lets less current through." },
    explain: "A light sensor's resistance falls when light shines on it. Light lets current through; darkness blocks it.",
    world: "Phones dim their screens using a light sensor near the camera.",
    tryThis: "Shine a torch on it, then cover it halfway. Can you make it dim?",
    concepts: ["sensor", "resistance"] },
  { id: "lab-7-2", unit: 7, level: "builder", emoji: "🧊", title: "Fridge light music",
    q: "How does a fridge know its door is open?", goal: "Play music when light shines on the sensor.",
    circuit: "battery B1 p n | ldr LDR1 p t | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["LDR1=bright -> SPK1=sound:melody", "LDR1=dark -> SPK1=quiet"],
    predict: { q: "Inside a closed fridge it's dark. When will this play?", options: ["When the door opens", "When the door closes"], answer: 0, why: "Opening the door lets light in, which lowers the sensor's resistance and triggers the chip." },
    explain: "The light sensor connects the trigger to + when it's bright.",
    world: "Some greeting cards play music when you open them, using light.",
    tryThis: "Make it a 'secret box alarm' that plays when someone opens your box.",
    concepts: ["sensor", "chip"] },
  { id: "lab-7-3", unit: 7, level: "engineer", emoji: "🌙", title: "Night light",
    q: "How does a light come on by itself when it gets dark?", goal: "Use a transistor to light an LED only in the dark.",
    circuit: "battery B1 p n | resistor R1 p b 10000 | ldr LDR1 b n | resistor R2 p c 100 | led D1 c d red | transistor Q1 d b n",
    checks: ["LDR1=bright -> D1=off", "LDR1=dark -> D1=on"],
    predict: { q: "In the dark, the sensor's resistance is very high. What happens at the transistor's base?", options: ["Its voltage rises and it switches on", "Its voltage falls and it switches off"], answer: 0, why: "The 10 kΩ resistor pulls the base up when the sensor stops pulling it down." },
    explain: "The resistor and sensor make a voltage divider. In the dark the base voltage rises above 0.7 V and the transistor switches the LED on.",
    world: "Street lights and night lights switch themselves on like this.", tryThis: "Swap R1 for 1 kΩ. Does it switch at a different darkness?",
    deeper: "The base sits at 3 V × R(sensor) ÷ (10 kΩ + R(sensor)). Bright: 0.03 V (off). Dark: about 3 V (on).",
    concepts: ["sensor", "transistor", "logic"] },
  { id: "lab-7-4", unit: 7, level: "inventor", emoji: "👤", title: "Shadow alarm",
    q: "How can an alarm sense a shadow?", goal: "Sound the siren when the sensor goes dark.",
    circuit: "battery B1 p n | resistor R1 p t 10000 | ldr LDR1 t n | siren SIR1 p n t o - - | speaker SPK1 o n",
    checks: ["LDR1=bright -> SPK1=quiet", "LDR1=dark -> SPK1=sound:police"],
    predict: { q: "In bright light the sensor pulls the trigger down to −. In the dark?", options: ["The resistor pulls it up: alarm!", "Nothing changes"], answer: 0, why: "The dark sensor lets almost nothing through, so the 10 kΩ resistor pulls the trigger HIGH." },
    explain: "A pull-up resistor and a sensor to − make an 'upside-down' (NOT) trigger: dark means ON.",
    world: "Security lights and alarms notice shadows passing.",
    tryThis: "Flip it: swap the sensor and the resistor. Now when does it sound?",
    concepts: ["sensor", "logic", "alarm"] },
  { id: "lab-7-5", unit: 7, level: "builder", emoji: "👏", title: "Clap for space sounds",
    q: "Can a circuit hear you?", goal: "Clap to trigger a space sound.",
    circuit: "battery B1 p n | piezo PZ1 t n | fx FX1 p n t o | speaker SPK1 o n",
    checks: ["PZ1=quiet -> SPK1=quiet", "PZ1=clap -> SPK1=sound:space"],
    predict: { q: "The buzzer disc is now a sensor. What does a clap do to it?", options: ["Shakes it and makes a tiny voltage", "Nothing"], answer: 0, why: "Shaking the disc's crystal makes a small voltage, enough to trigger the chip." },
    explain: "Some crystals make electricity when squeezed or shaken (piezoelectricity). The disc works both ways: speaker or sensor.",
    world: "Microphones, gas-stove lighters and some guitar pickups use this effect.",
    tryThis: "Clap louder, then softer. How quiet can you go? (Use the clap button, or turn on the microphone.)",
    concepts: ["sensor", "sound", "chip"] },
  { id: "lab-7-6", unit: 7, level: "builder", emoji: "✨", title: "Clap-on lights",
    q: "Can a clap switch on a light?", goal: "Make an LED flash when you clap.",
    circuit: "battery B1 p n | piezo PZ1 t n | fx FX1 p n t o | resistor R1 o b 100 | led D1 b n green",
    checks: ["PZ1=quiet -> D1=off", "PZ1=clap -> D1=flash"],
    predict: { q: "There's no speaker this time. How will you know it heard the clap?", options: ["The LED flashes", "You can't tell"], answer: 0, why: "The chip's output drives the LED instead of a speaker." },
    explain: "The same chip output can drive a light instead of a sound.",
    world: "Clap-on lights and some smart lamps react to sound.",
    tryThis: "Add the speaker too, so you see AND hear the clap.",
    concepts: ["sensor", "chip"] },
  { id: "lab-7-7", unit: 7, level: "builder", emoji: "🗣️", title: "Talk to the music box",
    q: "Can your voice start a tune?", goal: "Say something loudly to start a melody.",
    circuit: "battery B1 p n | piezo PZ1 t n | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["PZ1=quiet -> SPK1=quiet", "PZ1=clap -> SPK1=sound:melody"],
    predict: { q: "Your voice only shakes the disc for a moment. Will the whole tune play?", options: ["Yes", "Only a tiny bit"], answer: 0, why: "Once triggered, the melody chip finishes its tune." },
    explain: "Loud sounds shake the disc like a clap. The chip remembers it was triggered and plays to the end.",
    world: "Voice assistants listen for sound first, then work out what you said.",
    tryThis: "Whisper, talk and shout. Which ones trigger it?",
    concepts: ["sensor", "chip", "sound"] },
  { id: "lab-7-8", unit: 7, level: "builder", emoji: "🫳", title: "Touch light",
    q: "Can a lamp switch on with a touch?", goal: "Flash an LED when your finger touches the plate.",
    circuit: "battery B1 p n | touch T1 p t | melody MEL1 p n t o | resistor R1 o b 100 | led D1 b n red",
    checks: ["T1=no -> D1=off", "T1=yes -> D1=flash"],
    predict: { q: "Will a gloved finger work?", options: ["Yes", "No"], answer: 1, why: "A glove is an insulator, so no current flows from your finger." },
    explain: "Your skin conducts a tiny current. Phones' touch screens sense fingers too, in a cleverer way.",
    world: "Lift buttons and touch lamps can sense fingers without moving parts.",
    tryThis: "Try touching with a pencil tip (graphite) and with a plastic pen.",
    concepts: ["sensor", "conductor", "chip"] },
  { id: "lab-7-9", unit: 7, level: "builder", emoji: "🔦", title: "Light-controlled sounds",
    q: "Can light play sounds?", goal: "Shine and cover the light sensor to play space sounds.",
    circuit: "battery B1 p n | ldr LDR1 p t | fx FX1 p n t o | speaker SPK1 o n",
    checks: ["LDR1=bright -> SPK1=sound:space", "LDR1=dark -> SPK1=quiet"],
    predict: { q: "You wave your hand over the sensor. What happens?", options: ["The sounds start and stop", "Nothing"], answer: 0, why: "Each time the light returns, the trigger goes HIGH and the next sound plays." },
    explain: "Covering and uncovering the sensor turns the trigger off and on.",
    world: "Some musical instruments, like the theremin, are played without touching them.",
    tryThis: "Can you play a rhythm with your hand?",
    concepts: ["sensor", "chip", "sound"] },
  { id: "lab-7-10", unit: 7, level: "inventor", emoji: "🪞", title: "Reflection detector",
    q: "How can a robot tell black from white?", goal: "Shine the bulb on a card; the sensor notices the reflection.",
    circuit: "battery B1 p n | slide S1 p a | lamp L1 a n | ldr LDR1 p t | melody MEL1 p n t o | speaker SPK1 o n",
    checks: ["S1=on LDR1=lamp -> L1=on SPK1=sound:melody", "S1=on LDR1=dark -> L1=on SPK1=quiet", "S1=off LDR1=lamp -> SPK1=quiet"],
    predict: { q: "Which card reflects more light back to the sensor?", options: ["White", "Black"], answer: 0, why: "White reflects most light; black absorbs it." },
    explain: "The bulb shines, the card reflects (white) or absorbs (black), and the sensor tells the difference. (In the lab, choose 'lit by the lamp' for the white card and 'dark' for the black card.)",
    world: "Line-following robots and paper-sensing printers use reflection sensors.",
    tryThis: "Which would reflect more: a mirror or a black T-shirt?",
    concepts: ["sensor", "energy"] },
  { id: "lab-7-11", unit: 7, level: "builder", emoji: "📏", title: "Light meter",
    q: "How bright is it?", goal: "Build a meter that shows bright, dim and dark.",
    circuit: "battery B1 p n | ldr LDR1 p a | resistor R1 a b 100 | led D1 b n yellow",
    checks: ["LDR1=bright -> D1=on", "LDR1=dim -> D1=dim", "LDR1=dark -> D1=off"],
    predict: { q: "In a dim room, how will the LED look?", options: ["Bright", "Dim", "Off"], answer: 1, why: "Dim light gives the sensor a medium resistance, so a medium current flows." },
    explain: "The LED's brightness follows the light level: a simple measuring instrument.",
    world: "Cameras measure light to choose how long to take a picture.",
    tryThis: "Measure three rooms. Which is brightest at noon?",
    concepts: ["sensor", "resistance"] },
  { id: "lab-7-12", unit: 7, level: "inventor", emoji: "⏱️", title: "Clap timer light",
    q: "How can a light stay on after a clap?", goal: "Make an LED keep flashing for a few seconds after one clap.",
    circuit: "battery B1 p n | piezo PZ1 t n | melody MEL1 p n t o | resistor R1 o b 100 | led D1 b n green",
    checks: ["PZ1=clap -> D1=flash", "PZ1=quiet -> D1=off"],
    predict: { q: "The clap lasts a moment. How long will the LED flash?", options: ["A moment", "Until the tune ends"], answer: 1, why: "The chip plays its whole 6-second tune, keeping the output busy." },
    explain: "A short trigger, a longer action: that's a time delay.",
    world: "Stairwell lights stay on for a minute after you press the button.",
    tryThis: "What's a time delay you use every day? (Microwave? Toaster?)",
    concepts: ["sensor", "chip"] },

  // ───────── Unit 8 · Logic ─────────
  { id: "lab-8-1", unit: 8, level: "inventor", emoji: "🔀", title: "This OR that",
    q: "How can either of two switches turn on a light?", goal: "Light an LED if switch A OR button B is on.",
    circuit: "battery B1 p n | slide S1 p a | button BTN1 p a | resistor R1 a b 100 | led D1 b n red",
    checks: ["S1=off BTN1=up -> D1=off", "S1=on BTN1=up -> D1=on", "S1=off BTN1=down -> D1=on", "S1=on BTN1=down -> D1=on"],
    predict: { q: "Both are OFF. Will the LED light?", options: ["Yes", "No"], answer: 1, why: "OR needs at least one input ON." },
    explain: "Switches side by side make OR: the output is ON if any input is ON. Fill in its truth table.",
    world: "A car's inside light comes on if ANY door opens.",
    tryThis: "Write the truth table: 4 rows, 1 for ON, 0 for OFF.",
    concepts: ["logic", "parallel"] },
  { id: "lab-8-2", unit: 8, level: "inventor", emoji: "🔗", title: "This AND that",
    q: "How do you need both switches on?", goal: "Light an LED only if switch A AND button B are on.",
    circuit: "battery B1 p n | slide S1 p a | button BTN1 a b | resistor R1 b c 100 | led D1 c n red",
    checks: ["S1=off BTN1=up -> D1=off", "S1=on BTN1=up -> D1=off", "S1=off BTN1=down -> D1=off", "S1=on BTN1=down -> D1=on"],
    predict: { q: "Only the switch is ON. Will the LED light?", options: ["Yes", "No"], answer: 1, why: "AND needs every input ON." },
    explain: "Switches in a row make AND: the output is ON only if all inputs are ON.",
    world: "A mixer runs only if the lid is locked AND the button is pressed.",
    tryThis: "Write the AND truth table. How is it different from OR?",
    concepts: ["logic", "series"] },
  { id: "lab-8-3", unit: 8, level: "inventor", emoji: "🙃", title: "The NOT switch",
    q: "Can a switch turn a light OFF when you switch it ON?", goal: "Wire a switch so ON means the LED goes off.",
    circuit: "battery B1 p n | resistor R1 p a 100 | led D1 a n red | slide S1 a n",
    checks: ["S1=off -> D1=on", "S1=on -> D1=off"],
    predict: { q: "The switch makes a path around the LED. What happens when it's ON?", options: ["The LED goes off", "The LED gets brighter"], answer: 0, why: "Electricity takes the easy path through the switch and skips the LED." },
    explain: "NOT flips the input: ON becomes OFF. The resistor stops this from being a short circuit.",
    world: "A fridge light is ON when the door is NOT closed.",
    tryThis: "Why must the resistor stay? (Without it, the switch would short the battery!)",
    concepts: ["logic", "resistance", "short"] },
  { id: "lab-8-4", unit: 8, level: "inventor", emoji: "🚫", title: "Neither this NOR that",
    q: "How do you make a light that's on only when nothing is pressed?", goal: "LED on only if switch A and button B are both off.",
    circuit: "battery B1 p n | resistor R1 p a 100 | led D1 a n red | slide S1 a n | button BTN1 a n",
    checks: ["S1=off BTN1=up -> D1=on", "S1=on BTN1=up -> D1=off", "S1=off BTN1=down -> D1=off", "S1=on BTN1=down -> D1=off"],
    predict: { q: "How many of the 4 combinations light the LED?", options: ["1", "2", "3"], answer: 0, why: "Only when both are OFF: NOR is NOT-OR." },
    explain: "NOR is OR followed by NOT. Either input ON turns the LED OFF.",
    world: "A 'quiet room' light: on only when nobody presses a buzzer and no door is open.",
    tryThis: "Compare NOR's truth table with OR's. What do you notice?",
    concepts: ["logic", "parallel"] },
  { id: "lab-8-5", unit: 8, level: "inventor", emoji: "🧩", title: "NOT this AND that",
    q: "What is the opposite of AND?", goal: "LED off only when switch A and button B are both on.",
    circuit: "battery B1 p n | resistor R1 p a 100 | led D1 a n red | slide S1 a b | button BTN1 b n",
    checks: ["S1=off BTN1=up -> D1=on", "S1=on BTN1=up -> D1=on", "S1=off BTN1=down -> D1=on", "S1=on BTN1=down -> D1=off"],
    predict: { q: "Which combination turns the LED off?", options: ["Both ON", "Both OFF", "Any one ON"], answer: 0, why: "NAND is AND followed by NOT: only both ON gives OFF." },
    explain: "NAND (NOT-AND) is special: every other logic gate can be built from NANDs. Computer chips are full of them.",
    world: "Billions of NAND-like gates are inside every phone.",
    tryThis: "Write NAND's truth table, then AND's. Every answer is flipped!",
    concepts: ["logic", "series"] },
  { id: "lab-8-6", unit: 8, level: "inventor", emoji: "🪜", title: "Staircase light",
    q: "How can two switches far apart control one light?", goal: "Wire two two-way switches so either one changes the light.",
    circuit: "battery B1 p n | changeover SW1 p x y | changeover SW2 a x y | lamp L1 a n",
    checks: ["SW1=up SW2=up -> L1=on", "SW1=down SW2=down -> L1=on", "SW1=up SW2=down -> L1=off", "SW1=down SW2=up -> L1=off"],
    predict: { q: "The light is on. You flip one switch. Then you flip the other. What happens?", options: ["Off, then on again", "Off, then still off"], answer: 0, why: "Flipping either switch always changes the light." },
    explain: "The light is on when both switches point the same way. This logic is called XOR (or XNOR).",
    world: "Stairs and long corridors have a switch at each end wired like this.",
    tryThis: "Find a two-way switch at home and test it from both ends.",
    concepts: ["logic", "switch"] },
  { id: "lab-8-7", unit: 8, level: "inventor", emoji: "🔐", title: "Three-key safe",
    q: "How do you make a lock that needs three keys?", goal: "Light the green 'unlocked' LED only if all three are on.",
    circuit: "battery B1 p n | slide S1 p a | slide S2 a b | button BTN1 b c | resistor R1 c d 100 | led D1 d n green",
    checks: ["S1=on S2=on BTN1=down -> D1=on", "S1=on S2=off BTN1=down -> D1=off", "S1=off S2=on BTN1=down -> D1=off", "S1=on S2=on BTN1=up -> D1=off"],
    predict: { q: "With 3 switches, how many combinations are there?", options: ["3", "6", "8"], answer: 2, why: "Each switch doubles the choices: 2 × 2 × 2 = 8. Only one opens the safe." },
    explain: "A three-input AND: everything in a row must be closed.",
    world: "Bank vaults need two people's keys at once: an AND lock.",
    tryThis: "How many combinations would 4 switches have?",
    concepts: ["logic", "series"] },
  { id: "lab-8-8", unit: 8, level: "inventor", emoji: "💺", title: "Seatbelt alarm",
    q: "How does a car know you forgot your seatbelt?", goal: "Sound an alarm if someone sits down AND the belt is NOT fastened.",
    circuit: "battery B1 p n | button BTN1 p a | resistor R1 a t 10000 | slide S1 t n | siren SIR1 a n t o - - | speaker SPK1 o n",
    checks: ["BTN1=up S1=off -> SPK1=quiet", "BTN1=down S1=off -> SPK1=sound:police", "BTN1=down S1=on -> SPK1=quiet"],
    predict: { q: "Someone sits (button pressed) and fastens the belt (switch ON). Alarm?", options: ["Yes", "No"], answer: 1, why: "The belt switch pulls the trigger LOW: NOT fastened is needed for the alarm." },
    explain: "Seat AND NOT belt: the button powers the alarm, and the belt switch pulls the trigger down when fastened.",
    world: "Every modern car has this circuit, inside a computer chip.",
    tryThis: "Add a green LED that shows 'belt fastened'.",
    concepts: ["logic", "alarm"] },
];
